In [ ]:
from sklearn import datasets
import numpy as np
import random
import matplotlib.pyplot as plt
import time
import copy
from sklearn.metrics import euclidean_distances
%matplotlib auto

In [ ]:
# def DBSCAN(X,eps,min_Pts):
#     k=-1
#     neighbor_list=[]
#     omega_list=[]
#     gama=set([x for x in range(len(X))])
#     cluster=[-1 for _ in range(X)]
#     for i in range(len(X)):
#         neighbor_list.append(find_neighbor(i,X,eps))
#         if len(neighbor_list[-1]) >=min_Pts:
#             omega_list.append(i)
#     omega_list=set(omega_list)
#     while len(omega_list)>0:
#         gamma_old=copy.deepcopy(gama)
#         j=random.choice(list(omega_list))
#         k=k+1
#         Q=list()
#         Q.append(j)
#         while len(Q)>0:
#             q=Q[0]
#             Q.remove(q)
#             if len(neighbor_list[q])> min_Pts:
#                 delta=neighbor_list[q] & gama
#                 deltalist=list(delta)
#                 for i in range(len(delta)):
#                     Q.append(deltalist[i])
#                     gama=gama-delta
#         CK=gama_old-gama
#         CKlist=list(CK)
#         for i in range(len(CK)):
#             cluster[CKlist[i]]=k
#         omega_list=omega_list-CK
#     return cluster

In [ ]:
X1, y1 = datasets.make_circles(n_samples=2000, factor=.6, noise=.02)
X2, y2 = datasets.make_blobs(n_samples=400, n_features=2, centers=[[1.2, 1.2]], cluster_std=[[.1]], random_state=9)
X = np.concatenate((X1, X2))
eps = 1
MinPts = 10

In [4]:
eps = 0.2
MinPts = 5

ptses = []
dist = euclidean_distances(X)

In [5]:
for row in dist:
    density=np.sum(row<eps)
    pts=0
    if density>MinPts:
        pts=1
    elif density >1:
        pts=2
    else:
        pts=0
    ptses.append(pts)

In [6]:
cp_index=[]
for i ,v in enumerate(ptses):
    if v!=0:
        cp_index.append(i)

In [7]:
corePoints=X[cp_index,:]
coreDist=euclidean_distances(corePoints)

In [8]:
len(corePoints)

2400

In [9]:
dist

array([[ 0.        ,  1.23115205,  0.50428735, ...,  1.2172951 ,
         1.09211547,  0.96095053],
       [ 1.23115205,  0.        ,  1.43209146, ...,  2.27269609,
         2.18146735,  2.0488407 ],
       [ 0.50428735,  1.43209146,  0.        , ...,  0.84221083,
         0.75022929,  0.6190207 ],
       ...,
       [ 1.2172951 ,  2.27269609,  0.84221083, ...,  0.        ,
         0.14231207,  0.25832154],
       [ 1.09211547,  2.18146735,  0.75022929, ...,  0.14231207,
         0.        ,  0.13453878],
       [ 0.96095053,  2.0488407 ,  0.6190207 , ...,  0.25832154,
         0.13453878,  0.        ]])

In [10]:
coreDist

array([[ 0.        ,  1.23115205,  0.50428735, ...,  1.2172951 ,
         1.09211547,  0.96095053],
       [ 1.23115205,  0.        ,  1.43209146, ...,  2.27269609,
         2.18146735,  2.0488407 ],
       [ 0.50428735,  1.43209146,  0.        , ...,  0.84221083,
         0.75022929,  0.6190207 ],
       ...,
       [ 1.2172951 ,  2.27269609,  0.84221083, ...,  0.        ,
         0.14231207,  0.25832154],
       [ 1.09211547,  2.18146735,  0.75022929, ...,  0.14231207,
         0.        ,  0.13453878],
       [ 0.96095053,  2.0488407 ,  0.6190207 , ...,  0.25832154,
         0.13453878,  0.        ]])

In [11]:
cluster=dict()
i=0
for row in coreDist:
    cluster[i]=np.where(row<eps)[0]
    i+=1

In [12]:
len(cluster)

2400

In [13]:
cluster

{0: array([   0,   27,   52,   70,  172,  210,  227,  264,  307,  309,  324,
         429,  439,  474,  490,  526,  527,  660,  662,  698,  780,  789,
         797,  835,  840,  842,  846,  864,  865,  888,  914,  945, 1006,
        1011, 1016, 1047, 1176, 1321, 1330, 1331, 1332, 1342, 1366, 1368,
        1371, 1412, 1432, 1460, 1489, 1550, 1556, 1585, 1659, 1728, 1757,
        1811, 1827, 1835, 1839, 1851, 1911, 1942, 1998], dtype=int64),
 1: array([   1,   62,   64,   66,  102,  138,  158,  160,  170,  194,  203,
         225,  241,  246,  256,  257,  258,  270,  278,  285,  297,  305,
         323,  327,  384,  423,  442,  445,  446,  464,  483,  484,  501,
         573,  574,  592,  603,  639,  644,  690,  707,  715,  754,  796,
         801,  831,  851,  891,  893,  930,  950,  963,  976,  979,  996,
        1024, 1026, 1048, 1060, 1065, 1077, 1080, 1096, 1112, 1188, 1200,
        1212, 1219, 1232, 1253, 1267, 1272, 1295, 1354, 1375, 1383, 1390,
        1402, 1410, 1479, 1482, 1486, 1497, 1504, 1505, 1511, 1546, 1575,
        1580, 1601, 1637, 1650, 1668, 1679, 1721, 1726, 1773, 1778, 1796,
        1852, 1871, 1872, 1880, 1905, 1921, 1938, 1964, 1972, 1975], dtype=int64),
 2: array([   2,   11,   94,  129,  232,  250,  279,  298,  333,  338,  370,
         434,  492,  497,  539,  561,  588,  598,  617,  622,  625,  652,
         688,  691,  703,  709,  718,  769,  804,  825,  882,  991, 1013,
        1098, 1109, 1137, 1151, 1213, 1223, 1227, 1233, 1243, 1291, 1293,
        1325, 1364, 1428, 1449, 1454, 1526, 1535, 1547, 1610, 1615, 1669,
        1740, 1751, 1756, 1874, 1903, 1932, 1952, 1970, 1973, 1990], dtype=int64),
 3: array([   3,    9,   20,   81,  127,  128,  183,  205,  280,  299,  332,
         396,  420,  427,  435,  452,  521,  530,  537,  542,  553,  565,
         568,  623,  656,  753,  790,  795,  805,  819,  824,  863,  866,
         934, 1033, 1110, 1113, 1131, 1142, 1170, 1201, 1224, 1240, 1254,
        1306, 1320, 1324, 1373, 1524, 1532, 1568, 1576, 1594, 1605, 1629,
        1685, 1690, 1691, 1693, 1761, 1801, 1928], dtype=int64),
 4: array([   4,   38,   64,   66,   83,  138,  158,  160,  170,  194,  203,
         219,  225,  230,  261,  282,  285,  291,  308,  323,  327,  364,
         384,  423,  442,  459,  477,  484,  501,  574,  643,  690,  701,
         715,  738,  743,  746,  747,  775,  796,  829,  850,  852,  891,
         892,  893,  903,  955,  963,  996, 1024, 1030, 1043, 1060, 1071,
        1076, 1077, 1078, 1080, 1084, 1096, 1101, 1112, 1148, 1200, 1203,
        1238, 1261, 1287, 1294, 1295, 1303, 1323, 1354, 1375, 1383, 1386,
        1400, 1410, 1429, 1504, 1511, 1529, 1554, 1573, 1575, 1580, 1601,
        1637, 1658, 1668, 1682, 1726, 1771, 1796, 1834, 1866, 1871, 1898,
        1905, 1960, 1964, 1975, 1981], dtype=int64),
 5: array([   5,   22,   69,   71,  104,  108,  139,  163,  189,  274,  304,
         312,  340,  348,  372,  375,  401,  407,  460,  472,  510,  518,
         535,  548,  566,  602,  613,  657,  661,  665,  681,  756,  791,
         803,  839,  862,  873,  881, 1018, 1040, 1057, 1085, 1177, 1206,
        1208, 1209, 1252, 1264, 1265, 1315, 1381, 1517, 1519, 1597, 1613,
        1672, 1688, 1724, 1746, 1785, 1846, 1884, 1927, 1939], dtype=int64),
 6: array([   6,   34,  111,  175,  198,  213,  224,  343,  380,  390,  488,
         493,  511,  529,  614,  666,  755,  770,  809,  812,  837,  841,
         843,  874,  886,  901,  931,  937,  949,  962,  970,  985, 1005,
        1007, 1051, 1111, 1122, 1152, 1217, 1237, 1248, 1277, 1307, 1309,
        1314, 1405, 1409, 1424, 1444, 1551, 1564, 1592, 1683, 1723, 1739,
        1800, 1806, 1810, 1879, 1881, 1883, 1914, 1957, 1989], dtype=int64),
 7: array([   7,    8,   25,   30,   43,   61,   78,   97,  144,  169,  174,
         204,  229,  237,  268,  311,  320,  330,  367,  371,  414,  433,
         475,  476,  482,  487,  523,  525,  551,  556,  589,  594,  609,
         612,  629,  634,  655,  673,  680,  708,  713,  717,  719,  783,
         806,  816,  817,  855,  857,  869,  871,  875,  925,  933,  935,
         938,  939,  951,  960,  965,  966,  995, 1025, 1028, 1036, 1061,
        1072, 1073, 1079, 1092, 1145, 1146, 1157, 1181, 1231, 1234, 1242,
        1245, 1260, 1285, 1305, 1326, 1329, 1374, 1401, 1407, 1427, 1453,
        1459, 1570, 1598, 1621, 1625, 1656, 1657, 1666, 1667, 1673, 1689,
        1703, 1705, 1753, 1782, 1792, 1819, 1848, 1863, 1896, 1912, 1959,
        1997], dtype=int64),
 8: array([   7,    8,   25,   30,   43,   61,   78,   87,  101,  144,  169,
         174,  204,  229,  237,  293,  311,  320,  330,  367,  371,  414,
         433,  475,  482,  487,  494,  523,  525,  556,  589,  594,  609,
         612,  629,  634,  655,  673,  680,  708,  713,  717,  719,  749,
         783,  806,  816,  817,  855,  869,  871,  875,  925,  933,  935,
         938,  939,  951,  960,  965,  966, 1025, 1028, 1036, 1061, 1072,
        1073, 1079, 1092, 1145, 1146, 1181, 1231, 1234, 1242, 1245, 1260,
        1285, 1305, 1326, 1329, 1374, 1401, 1407, 1427, 1453, 1459, 1570,
        1598, 1621, 1625, 1656, 1657, 1666, 1667, 1689, 1703, 1705, 1753,
        1764, 1782, 1792, 1819, 1848, 1863, 1912, 1917, 1922, 1959, 1997], dtype=int64),
 9: array([   3,    9,   73,  127,  171,  183,  242,  280,  328,  396,  420,
         432,  435,  452,  521,  542,  553,  565,  568,  623,  656,  740,
         745,  753,  782,  790,  795,  798,  819,  824,  934, 1020, 1110,
        1113, 1131, 1142, 1178, 1201, 1224, 1240, 1254, 1292, 1306, 1311,
        1320, 1363, 1373, 1388, 1510, 1518, 1524, 1548, 1568, 1578, 1594,
        1600, 1635, 1685, 1693, 1761, 1774, 1837], dtype=int64),
 10: array([  10,   23,   24,   42,   44,   45,   50,   67,  100,  105,  110,
         141,  176,  179,  196,  220,  287,  296,  336,  359,  374,  377,
         385,  447,  466,  498,  499,  502,  517,  532,  547,  560,  564,
         581,  605,  619,  648,  676,  693,  742,  800,  802,  808,  828,
         838,  853,  880,  884,  889,  890,  916,  946,  972,  973,  977,
         980,  989, 1010, 1023, 1031, 1067, 1083, 1087, 1089, 1103, 1105,
        1121, 1153, 1154, 1210, 1259, 1276, 1282, 1322, 1328, 1349, 1350,
        1358, 1425, 1431, 1446, 1456, 1463, 1477, 1531, 1553, 1555, 1562,
        1584, 1618, 1678, 1697, 1715, 1817, 1845, 1850, 1869, 1890, 1908,
        1935, 1943, 1965], dtype=int64),
 11: array([   2,   11,   28,   35,  129,  155,  173,  250,  264,  279,  286,
         324,  333,  354,  434,  497,  513,  539,  561,  598,  617,  622,
         625,  679,  691,  709,  718,  769,  799,  804,  825,  876,  882,
        1013, 1086, 1098, 1137, 1193, 1233, 1243, 1250, 1293, 1325, 1331,
        1342, 1366, 1449, 1454, 1460, 1480, 1526, 1535, 1610, 1653, 1669,
        1681, 1740, 1751, 1844, 1874, 1885, 1903, 1915, 1952, 1970], dtype=int64),
 12: array([  12,   38,   51,   54,  202,  206,  207,  212,  218,  219,  222,
         230,  261,  262,  282,  283,  290,  322,  346,  373,  405,  430,
         459,  461,  477,  491,  524,  543,  569,  577,  590,  593,  604,
         606,  628,  668,  670,  701,  738,  743,  746,  807,  829,  845,
         850,  854,  892,  894,  903,  919,  964,  975,  990, 1003, 1030,
        1032, 1043, 1071, 1078, 1084, 1101, 1102, 1148, 1158, 1166, 1179,
        1205, 1221, 1256, 1261, 1268, 1279, 1283, 1297, 1302, 1319, 1323,
        1377, 1378, 1386, 1400, 1403, 1429, 1458, 1472, 1473, 1490, 1533,
        1573, 1604, 1614, 1702, 1748, 1771, 1790, 1795, 1834, 1866, 1873,
        1893, 1897, 1898, 1907, 1931, 1945, 1949, 1981], dtype=int64),
 13: array([  13,   17,   24,   25,   43,   44,   68,   75,   87,  101,  105,
         144,  204,  229,  284,  293,  311,  342,  382,  409,  475,  494,
         498,  504,  517,  547,  550,  556,  589,  594,  607,  619,  653,
         658,  676,  696,  713,  742,  749,  783,  808,  816,  817,  821,
         880,  889,  951,  958,  960,  966,  969,  972,  978,  989,  992,
        1028, 1115, 1121, 1128, 1136, 1145, 1153, 1172, 1181, 1195, 1239,
        1255, 1258, 1259, 1260, 1322, 1326, 1327, 1329, 1348, 1350, 1356,
        1367, 1393, 1398, 1401, 1407, 1417, 1427, 1436, 1453, 1470, 1562,
        1598, 1644, 1674, 1692, 1705, 1722, 1753, 1764, 1782, 1848, 1850,
        1863, 1875, 1908, 1917, 1922, 1997], dtype=int64),
 14: array([  14,   20,   46,   48,   81,  128,  152,  178,  184,  195,  200,
         205,  216,  253,  271,  277,  299,  332,  427,  507,  530,  537,
         544,  608,  682,  716,  751,  805,  863,  866,  926,  947,  952,
        1021, 1033, 1046, 1054, 1108, 1125, 1159, 1170, 1202, 1228, 1312,
        1324, 1360, 1419, 1503, 1532, 1572, 1576, 1605, 1629, 1690, 1691,
        1801, 1804, 1877, 1928, 1958, 1987], dtype=int64),
 15: array([  15,   58,   59,  116,  151,  177,  188,  193,  217,  239,  245,
         251,  255,  266,  292,  321,  355,  357,  365,  383,  394,  404,
         415,  428,  467,  515,  516,  562,  571,  575,  611,  630,  638,
         654,  672,  686,  723,  730,  785,  860,  867,  897,  943, 1015,
        1038, 1045, 1066, 1093, 1147, 1164, 1167, 1168, 1220, 1246, 1281,
        1335, 1353, 1384, 1392, 1397, 1467, 1474, 1487, 1495, 1514, 1520,
        1523, 1530, 1543, 1561, 1567, 1587, 1596, 1606, 1616, 1624, 1643,
        1647, 1670, 1695, 1720, 1736, 1744, 1766, 1781, 1786, 1836, 1849,
        1860, 1882, 1891, 1918, 1923, 1925, 1947, 1971, 1978, 1988, 1991], dtype=int64),
 16: array([  16,   53,  114,  166,  254,  303,  306,  317,  392,  403,  453,
         572,  578,  627,  631,  632,  645,  725,  726,  733,  781,  811,
         834,  879,  887,  895,  900,  971,  981, 1014, 1044, 1059, 1068,
        1094, 1097, 1127, 1185, 1187, 1189, 1204, 1241, 1251, 1270, 1344,
        1352, 1369, 1391, 1414, 1418, 1433, 1515, 1565, 1652, 1662, 1664,
        1701, 1711, 1775, 1821, 1825, 1838, 1854, 1864, 1904, 1934], dtype=int64),
 17: array([  13,   17,   23,   24,   25,   44,   45,   68,   75,   87,  101,
         105,  179,  284,  293,  336,  342,  359,  382,  409,  494,  498,
         504,  517,  547,  550,  564,  605,  607,  619,  653,  658,  676,
         693,  696,  713,  742,  749,  783,  800,  808,  817,  821,  853,
         880,  889,  946,  958,  969,  972,  978,  989,  992, 1010, 1031,
        1083, 1105, 1115, 1121, 1128, 1136, 1145, 1153, 1172, 1195, 1239,
        1255, 1258, 1259, 1322, 1327, 1328, 1348, 1350, 1356, 1367, 1393,
        1398, 1417, 1425, 1436, 1453, 1456, 1470, 1562, 1644, 1674, 1678,
        1692, 1697, 1722, 1764, 1845, 1848, 1850, 1869, 1875, 1908, 1917,
        1922, 1997], dtype=int64),
 18: array([  18,   53,   56,   71,  104,  139,  306,  312,  319,  340,  348,
         453,  472,  535,  566,  610,  613,  632,  636,  657,  661,  665,
         733,  737,  756,  781,  862,  873,  971, 1014, 1040, 1059, 1085,
        1097, 1177, 1185, 1187, 1204, 1208, 1209, 1241, 1252, 1264, 1265,
        1270, 1352, 1381, 1391, 1418, 1445, 1517, 1566, 1597, 1613, 1664,
        1711, 1775, 1814, 1884, 1888, 1904, 1936, 1974], dtype=int64),
 19: array([  19,   49,   88,  149,  162,  182,  294,  300,  362,  366,  369,
         441,  479,  496,  509,  540,  554,  699,  721,  731,  771,  774,
         779,  896,  913,  932,  936,  968, 1012, 1114, 1118, 1139, 1161,
        1235, 1288, 1313, 1336, 1346, 1396, 1439, 1450, 1457, 1465, 1485,
        1488, 1500, 1508, 1509, 1528, 1552, 1563, 1586, 1602, 1660, 1677,
        1741, 1752, 1767, 1770, 1802, 1913], dtype=int64),
 20: array([   3,   14,   20,   48,   81,  128,  178,  184,  195,  200,  205,
         216,  253,  271,  277,  299,  332,  427,  452,  507,  530,  537,
         542,  553,  565,  608,  623,  716,  751,  805,  863,  866,  926,
         952, 1021, 1033, 1046, 1054, 1108, 1125, 1159, 1170, 1224, 1306,
        1312, 1324, 1360, 1419, 1503, 1532, 1572, 1576, 1605, 1629, 1690,
        1691, 1801, 1804, 1877, 1928, 1958], dtype=int64),
 21: array([  21,   34,   47,  103,  198,  211,  214,  224,  273,  276,  343,
         349,  353,  380,  389,  390,  531,  557,  559,  583,  614,  666,
         770,  793,  794,  809,  812,  830,  847,  858,  874,  886,  918,
         931,  949,  970,  974,  999, 1034, 1051, 1123, 1129, 1138, 1169,
        1237, 1277, 1284, 1307, 1309, 1405, 1424, 1501, 1551, 1564, 1592,
        1712, 1723, 1779, 1783, 1798, 1806, 1810, 1855, 1883, 1976], dtype=int64),
 22: array([   5,   22,   39,   69,   82,  106,  108,  124,  163,  189,  267,
         274,  304,  344,  372,  375,  401,  407,  419,  460,  471,  510,
         518,  548,  580,  602,  613,  642,  681,  791,  803,  839,  881,
         911,  921,  961, 1000, 1018, 1057, 1206, 1280, 1315, 1334, 1370,
        1381, 1385, 1451, 1462, 1519, 1599, 1609, 1636, 1648, 1672, 1688,
        1704, 1724, 1746, 1785, 1822, 1831, 1846, 1906, 1927, 1939], dtype=int64),
 23: array([  10,   17,   23,   24,   42,   44,   45,   68,  100,  105,  110,
         141,  176,  179,  196,  220,  284,  287,  336,  342,  359,  374,
         385,  447,  466,  498,  499,  504,  517,  532,  547,  550,  560,
         564,  581,  605,  619,  648,  653,  658,  676,  693,  742,  800,
         808,  821,  828,  838,  853,  880,  884,  889,  916,  946,  972,
         989, 1010, 1031, 1067, 1083, 1087, 1105, 1115, 1121, 1153, 1210,
        1239, 1258, 1259, 1276, 1322, 1328, 1348, 1350, 1356, 1358, 1367,
        1393, 1398, 1417, 1425, 1431, 1446, 1456, 1470, 1477, 1555, 1562,
        1584, 1678, 1692, 1697, 1817, 1845, 1850, 1869, 1875, 1890, 1908,
        1943, 1965], dtype=int64),
 24: array([  10,   13,   17,   23,   24,   44,   45,   68,   75,  100,  105,
         176,  179,  196,  220,  284,  336,  342,  359,  382,  385,  409,
         466,  498,  504,  517,  532,  547,  550,  564,  581,  605,  607,
         619,  648,  653,  658,  676,  693,  696,  742,  800,  808,  821,
         838,  853,  880,  889,  946,  958,  969,  972,  978,  989, 1010,
        1031, 1083, 1105, 1115, 1121, 1128, 1136, 1153, 1172, 1195, 1210,
        1239, 1255, 1258, 1259, 1276, 1322, 1327, 1328, 1348, 1350, 1356,
        1358, 1367, 1393, 1398, 1417, 1425, 1431, 1436, 1446, 1456, 1470,
        1477, 1555, 1562, 1584, 1644, 1678, 1692, 1697, 1722, 1817, 1845,
        1850, 1869, 1875, 1908, 1943, 1965], dtype=int64),
 25: array([   7,    8,   13,   17,   25,   43,   61,   68,   75,   87,  101,
         144,  204,  229,  284,  293,  311,  342,  382,  409,  414,  433,
         475,  494,  504,  523,  550,  556,  589,  594,  607,  612,  653,
         658,  673,  696,  708,  713,  717,  719,  749,  783,  816,  817,
         821,  855,  869,  880,  951,  958,  960,  966,  969,  978,  992,
        1025, 1028, 1036, 1072, 1115, 1128, 1136, 1145, 1172, 1181, 1195,
        1231, 1234, 1239, 1245, 1255, 1258, 1260, 1326, 1327, 1329, 1356,
        1367, 1374, 1393, 1398, 1401, 1407, 1417, 1427, 1436, 1453, 1470,
        1598, 1621, 1625, 1644, 1656, 1674, 1689, 1692, 1705, 1722, 1753,
        1764, 1782, 1848, 1863, 1875, 1917, 1922, 1959, 1997], dtype=int64),
 26: array([  26,   42,   50,   58,   67,  100,  110,  122,  141,  146,  176,
         193,  196,  239,  251,  287,  296,  302,  310,  357,  374,  377,
         383,  394,  404,  447,  466,  467,  499,  502,  560,  571,  575,
         581,  586,  611,  626,  648,  654,  723,  730,  802,  828,  838,
         884,  890,  916,  973,  977,  980, 1015, 1023, 1035, 1039, 1045,
        1066, 1067, 1087, 1089, 1103, 1135, 1154, 1173, 1190, 1196, 1246,
        1282, 1349, 1358, 1397, 1446, 1463, 1467, 1474, 1487, 1495, 1520,
        1530, 1531, 1553, 1555, 1567, 1596, 1606, 1618, 1663, 1684, 1715,
        1720, 1736, 1744, 1766, 1817, 1836, 1860, 1889, 1890, 1918, 1923,
        1925, 1935, 1943, 1947, 1965, 1971, 1991, 1994], dtype=int64),
 27: array([   0,   27,   52,   70,  172,  210,  227,  264,  307,  309,  324,
         429,  439,  474,  490,  527,  660,  662,  698,  789,  797,  835,
         840,  842,  846,  864,  865,  888,  914,  945, 1006, 1011, 1016,
        1047, 1176, 1321, 1330, 1331, 1332, 1342, 1366, 1368, 1371, 1412,
        1432, 1460, 1489, 1550, 1556, 1585, 1659, 1728, 1811, 1827, 1835,
        1839, 1851, 1915, 1998], dtype=int64),
 28: array([  11,   28,   35,  129,  155,  172,  173,  210,  264,  279,  286,
         324,  333,  354,  429,  434,  490,  513,  539,  561,  598,  622,
         625,  679,  691,  709,  718,  769,  797,  799,  804,  835,  876,
         882, 1011, 1013, 1086, 1098, 1193, 1243, 1250, 1293, 1331, 1342,
        1366, 1454, 1460, 1480, 1526, 1550, 1653, 1669, 1681, 1740, 1751,
        1844, 1874, 1885, 1915, 1970, 1998], dtype=int64),
 29: array([  29,   74,   91,   93,  118,  123,  130,  154,  180,  226,  275,
         329,  334,  335,  378,  418,  437,  465,  469,  470,  473,  495,
         500,  508,  519,  546,  596,  624,  640,  674,  697,  706,  729,
         741,  748,  762,  763,  765,  788,  826,  827,  848,  859,  870,
         872,  902, 1004, 1009, 1041, 1050, 1119, 1130, 1149, 1156, 1175,
        1197, 1215, 1222, 1273, 1274, 1301, 1308, 1343, 1345, 1359, 1411,
        1416, 1430, 1434, 1461, 1464, 1478, 1491, 1499, 1506, 1512, 1542,
        1549, 1559, 1581, 1622, 1632, 1646, 1654, 1696, 1707, 1708, 1729,
        1760, 1768, 1794, 1807, 1813, 1832, 1878, 1887, 1901, 1930, 1933,
        1944, 1946], dtype=int64),
 30: array([   7,    8,   30,   37,   61,   78,   90,   97,  165,  169,  174,
         231,  237,  263,  268,  320,  330,  367,  371,  381,  414,  433,
         475,  476,  478,  482,  487,  523,  525,  551,  609,  612,  629,
         634,  655,  673,  680,  708,  717,  719,  806,  832,  855,  857,
         869,  871,  875,  925,  933,  935,  938,  939,  959,  960,  965,
         995,  998, 1017, 1022, 1025, 1036, 1061, 1072, 1073, 1079, 1092,
        1146, 1157, 1181, 1194, 1198, 1225, 1231, 1234, 1242, 1245, 1275,
        1285, 1298, 1305, 1340, 1374, 1415, 1459, 1537, 1538, 1570, 1583,
        1621, 1625, 1656, 1657, 1666, 1667, 1673, 1689, 1698, 1703, 1730,
        1788, 1792, 1819, 1842, 1896, 1912, 1953, 1959], dtype=int64),
 31: array([  31,   89,   95,  120,  126,  140,  161,  215,  240,  249,  289,
         315,  361,  363,  387,  410,  448,  534,  552,  567,  576,  585,
         597,  620,  650,  705,  760,  792,  815,  844,  849,  915,  922,
         984, 1019, 1062, 1095, 1117, 1132, 1140, 1180, 1183, 1184, 1304,
        1394, 1448, 1468, 1516, 1544, 1607, 1623, 1627, 1628, 1634, 1713,
        1727, 1758, 1762, 1784, 1828, 1910, 1993], dtype=int64),
 32: array([  32,   60,   84,  115,  136,  167,  186,  209,  228,  236,  269,
         301,  352,  395,  422,  450,  454,  455,  506,  659,  678,  734,
         766,  776,  777,  822,  836,  905,  924,  941,  986, 1063, 1090,
        1106, 1144, 1244, 1296, 1317, 1318, 1395, 1421, 1435, 1469, 1560,
        1590, 1639, 1651, 1661, 1675, 1710, 1725, 1733, 1735, 1743, 1799,
        1818, 1826, 1868, 1899, 1919, 1963, 1979, 1986], dtype=int64),
 33: array([  33,   41,   63,   96,  134,  135,  164,  316,  326,  399,  400,
         412,  436,  438,  443,  444,  462,  512,  528,  541,  545,  641,
         647,  667,  692,  724,  820,  898,  904,  942,  987, 1037, 1053,
        1074, 1081, 1082, 1165, 1182, 1192, 1355, 1443, 1481, 1484, 1522,
        1527, 1571, 1582, 1617, 1671, 1676, 1718, 1734, 1738, 1747, 1769,
        1791, 1803, 1840, 1841, 1900, 1902, 1940, 1951, 1977, 1996], dtype=int64),
 34: array([   6,   21,   34,  103,  111,  175,  198,  213,  224,  276,  343,
         380,  389,  390,  493,  529,  557,  559,  614,  666,  755,  770,
         809,  812,  841,  874,  886,  931,  949,  970,  985,  999, 1005,
        1007, 1051, 1111, 1122, 1152, 1217, 1237, 1248, 1277, 1307, 1309,
        1314, 1405, 1409, 1424, 1551, 1564, 1592, 1712, 1723, 1739, 1783,
        1806, 1810, 1879, 1881, 1883, 1914, 1957, 1989], dtype=int64),
 35: array([  11,   28,   35,  129,  155,  172,  173,  210,  264,  279,  286,
         324,  354,  429,  434,  490,  513,  539,  561,  622,  625,  679,

In [14]:
for k,v in cluster.items():
    print(k,len(v))

0 63
1 109
2 65
3 62
4 104
5 64
6 64
7 111
8 110
9 62
10 102
11 65
12 107
13 105
14 61
15 99
16 65
17 101
18 63
19 61
20 61
21 65
22 65
23 101
24 105
25 108
26 107
27 59
28 61
29 101
30 107
31 62
32 63
33 65
34 63
35 60
36 109
37 105
38 106
39 65
40 106
41 68
42 108
43 105
44 103
45 99
46 64
47 63
48 64
49 65
50 104
51 110
52 63
53 67
54 101
55 62
56 62
57 107
58 106
59 104
60 63
61 104
62 105
63 65
64 102
65 67
66 104
67 107
68 108
69 64
70 60
71 62
72 104
73 66
74 108
75 106
76 101
77 106
78 105
79 105
80 110
81 62
82 63
83 106
84 67
85 105
86 106
87 109
88 61
89 61
90 100
91 112
92 61
93 100
94 65
95 63
96 64
97 102
98 98
99 105
100 106
101 107
102 107
103 64
104 66
105 105
106 66
107 105
108 58
109 107
110 104
111 62
112 67
113 104
114 64
115 59
116 104
117 64
118 101
119 103
120 66
121 102
122 104
123 109
124 66
125 105
126 64
127 63
128 63
129 65
130 106
131 105
132 66
133 59
134 62
135 64
136 65
137 104
138 105
139 59
140 60
141 103
142 107
143 101
144 104
145 101
146 106
147 58
148 105
149 65
150 64
151 103
152 63
153 107
154 107
155 63
156 97
157 107
158 106
159 60
160 105
161 61
162 60
163 68
164 65
165 97
166 64
167 60
168 108
169 114
170 106
171 60
172 60
173 60
174 106
175 63
176 106
177 102
178 64
179 107
180 109
181 104
182 61
183 65
184 63
185 99
186 62
187 101
188 103
189 65
190 104
191 66
192 64
193 106
194 108
195 61
196 105
197 63
198 66
199 108
200 61
201 63
202 109
203 105
204 98
205 61
206 110
207 104
208 61
209 63
210 60
211 63
212 109
213 64
214 60
215 61
216 63
217 102
218 104
219 110
220 99
221 60
222 106
223 64
224 66
225 106
226 106
227 64
228 61
229 106
230 103
231 102
232 70
233 63
234 62
235 106
236 61
237 106
238 64
239 101
240 63
241 102
242 61
243 67
244 104
245 104
246 105
247 107
248 61
249 64
250 63
251 100
252 107
253 62
254 62
255 100
256 100
257 104
258 109
259 63
260 65
261 106
262 107
263 102
264 62
265 106
266 109
267 63
268 104
269 61
270 103
271 60
272 65
273 62
274 63
275 109
276 60
277 63
278 108
279 68
280 64
281 63
282 107
283 111
284 104
285 97
286 58
287 100
288 103
289 60
290 109
291 111
292 100
293 109
294 62
295 103
296 106
297 95
298 66
299 67
300 65
301 61
302 103
303 63
304 68
305 103
306 62
307 62
308 105
309 63
310 107
311 109
312 64
313 67
314 105
315 60
316 63
317 62
318 62
319 62
320 102
321 105
322 106
323 102
324 62
325 67
326 62
327 105
328 67
329 107
330 106
331 101
332 64
333 65
334 105
335 108
336 106
337 104
338 64
339 105
340 65
341 111
342 110
343 64
344 62
345 106
346 106
347 113
348 63
349 61
350 67
351 100
352 59
353 62
354 58
355 105
356 63
357 101
358 64
359 107
360 107
361 64
362 65
363 63
364 106
365 99
366 58
367 110
368 64
369 66
370 65
371 102
372 62
373 105
374 109
375 62
376 107
377 106
378 104
379 65
380 63
381 104
382 109
383 106
384 105
385 111
386 65
387 60
388 67
389 61
390 65
391 106
392 66
393 64
394 105
395 62
396 65
397 107
398 104
399 62
400 65
401 66
402 62
403 64
404 104
405 105
406 107
407 63
408 64
409 109
410 62
411 64
412 64
413 63
414 108
415 102
416 63
417 108
418 107
419 64
420 62
421 110
422 62
423 102
424 63
425 106
426 60
427 64
428 104
429 61
430 106
431 106
432 64
433 110
434 65
435 61
436 65
437 102
438 62
439 63
440 107
441 61
442 104
443 65
444 66
445 100
446 103
447 106
448 61
449 109
450 63
451 62
452 63
453 62
454 62
455 63
456 63
457 101
458 62
459 100
460 59
461 108
462 63
463 107
464 104
465 108
466 105
467 101
468 63
469 105
470 107
471 66
472 62
473 107
474 58
475 106
476 105
477 107
478 102
479 62
480 64
481 64
482 107
483 103
484 104
485 109
486 108
487 107
488 65
489 64
490 61
491 105
492 65
493 63
494 111
495 107
496 62
497 66
498 103
499 108
500 110
501 101
502 100
503 107
504 108
505 104
506 64
507 63
508 103
509 58
510 65
511 63
512 65
513 60
514 102
515 104
516 104
517 107
518 64
519 104
520 64
521 65
522 108
523 110
524 99
525 107
526 63
527 63
528 65
529 62
530 66
531 64
532 106
533 104
534 61
535 65
536 109
537 65
538 102
539 66
540 63
541 65
542 65
543 106
544 63
545 62
546 107
547 104
548 61
549 103
550 110
551 108
552 63
553 65
554 61
555 64
556 105
557 61
558 107
559 65
560 104
561 64
562 106
563 107
564 108
565 61
566 61
567 63
568 61
569 103
570 65
571 104
572 65
573 109
574 104
575 104
576 63
577 105
578 60
579 65
580 65
581 108
582 107
583 63
584 61
585 62
586 103
587 105
588 63
589 104
590 106
591 105
592 107
593 108
594 106
595 103
596 102
597 61
598 65
599 103
600 102
601 67
602 66
603 103
604 111
605 111
606 105
607 105
608 64
609 104
610 61
611 108
612 112
613 62
614 67
615 101
616 62
617 64
618 63
619 105
620 60
621 64
622 63
623 63
624 108
625 66
626 100
627 63
628 109
629 109
630 102
631 68
632 62
633 105
634 113
635 109
636 60
637 103
638 106
639 107
640 104
641 64
642 60
643 107
644 108
645 65
646 65
647 68
648 103
649 105
650 64
651 102
652 66
653 111
654 107
655 108
656 61
657 62
658 106
659 64
660 62
661 61
662 64
663 61
664 66
665 67
666 65
667 63
668 110
669 67
670 107
671 113
672 102
673 109
674 103
675 106
676 104
677 67
678 65
679 60
680 111
681 65
682 66
683 106
684 104
685 111
686 108
687 62
688 64
689 67
690 104
691 61
692 68
693 112
694 105
695 63
696 109
697 108
698 60
699 62
700 104
701 105
702 62
703 64
704 62
705 61
706 107
707 105
708 109
709 65
710 104
711 105
712 65
713 110
714 105
715 105
716 62
717 112
718 65
719 111
720 105
721 58
722 107
723 106
724 65
725 66
726 66
727 67
728 104
729 105
730 104
731 63
732 63
733 63
734 65
735 108
736 110
737 61
738 107
739 66
740 62
741 108
742 106
743 109
744 105
745 67
746 104
747 104
748 102
749 104
750 107
751 63
752 107
753 63
754 107
755 62
756 64
757 113
758 63
759 107
760 63
761 61
762 103
763 106
764 66
765 106
766 58
767 59
768 109
769 65
770 67
771 62
772 106
773 107
774 61
775 102
776 61
777 65
778 67
779 60
780 61
781 67
782 59
783 108
784 106
785 106
786 63
787 66
788 106
789 63
790 67
791 61
792 63
793 60
794 61
795 64
796 103
797 62
798 61
799 60
800 108
801 99
802 107
803 61
804 66
805 62
806 107
807 108
808 104
809 66
810 109
811 62
812 67
813 66
814 62
815 62
816 108
817 105
818 107
819 65
820 65
821 102
822 65
823 62
824 61
825 65
826 102
827 102
828 105
829 103
830 61
831 105
832 106
833 102
834 65
835 62
836 63
837 65
838 100
839 65
840 59
841 64
842 62
843 63
844 63
845 109
846 62
847 61
848 99
849 60
850 103
851 106
852 101
853 106
854 107
855 108
856 67
857 103
858 60
859 105
860 104
861 109
862 63
863 65
864 59
865 59
866 64
867 100
868 106
869 112
870 111
871 107
872 104
873 62
874 65
875 112
876 61
877 62
878 104
879 65
880 102
881 68
882 64
883 101
884 98
885 65
886 64
887 62
888 60
889 108
890 107
891 106
892 113
893 101
894 107
895 64
896 60
897 103
898 65
899 107
900 64
901 63
902 104
903 109
904 64
905 62
906 62
907 60
908 102
909 105
910 106
911 59
912 107
913 66
914 60
915 64
916 105
917 104
918 64
919 103
920 101
921 62
922 64
923 105
924 63
925 107
926 59
927 59
928 104
929 104
930 103
931 63
932 65
933 106
934 64
935 107
936 61
937 63
938 104
939 109
940 64
941 64
942 66
943 104
944 108
945 64
946 104
947 64
948 61
949 63
950 103
951 108
952 63
953 65
954 109
955 104
956 62
957 67
958 109
959 107
960 110
961 65
962 67
963 105
964 105
965 107
966 108
967 64
968 61
969 109
970 66
971 64
972 106
973 107
974 62
975 99
976 103
977 104
978 106
979 109
980 108
981 62
982 96
983 110
984 61
985 63
986 63
987 63
988 108
989 105
990 107
991 66
992 104
993 109
994 63
995 104
996 104
997 62
998 104
999 64
1000 67
1001 62
1002 62
1003 107
1004 107
1005 63
1006 64
1007 64
1008 104
1009 107
1010 103
1011 61
1012 62
1013 64
1014 63
1015 108
1016 65
1017 105
1018 66
1019 61
1020 60
1021 62
1022 107
1023 106
1024 100
1025 106
1026 110
1027 62
1028 110
1029 104
1030 101
1031 104
1032 103
1033 64
1034 61
1035 105
1036 107
1037 63
1038 102
1039 105
1040 65
1041 110
1042 59
1043 110
1044 64
1045 101
1046 62
1047 61
1048 104
1049 113
1050 105
1051 64
1052 99
1053 65
1054 61
1055 65
1056 106
1057 61
1058 104
1059 62
1060 103
1061 104
1062 66
1063 61
1064 113
1065 106
1066 104
1067 108
1068 68
1069 62
1070 64
1071 105
1072 110
1073 107
1074 63
1075 105
1076 99
1077 105
1078 103
1079 109
1080 99
1081 63
1082 62
1083 106
1084 109
1085 62
1086 62
1087 105
1088 62
1089 102
1090 63
1091 105
1092 106
1093 107
1094 66
1095 62
1096 103
1097 62
1098 66
1099 64
1100 62
1101 106
1102 105
1103 100
1104 107
1105 106
1106 62
1107 62
1108 59
1109 66
1110 66
1111 63
1112 105
1113 64
1114 61
1115 108
1116 104
1117 63
1118 60
1119 108
1120 67
1121 101
1122 63
1123 62
1124 103
1125 64
1126 112
1127 63
1128 108
1129 63
1130 109
1131 63
1132 59
1133 106
1134 65
1135 103
1136 108
1137 65
1138 63
1139 64
1140 63
1141 63
1142 65
1143 106
1144 63
1145 108
1146 107
1147 105
1148 104
1149 103
1150 104
1151 65
1152 62
1153 104
1154 106
1155 104
1156 110
1157 105
1158 107
1159 61
1160 105
1161 62
1162 65
1163 111
1164 105
1165 65
1166 107
1167 104
1168 103
1169 63
1170 64
1171 106
1172 107
1173 98
1174 107
1175 104
1176 60
1177 68
1178 60
1179 107
1180 61
1181 109
1182 66
1183 62
1184 60
1185 67
1186 105
1187 67
1188 103
1189 62
1190 103
1191 63
1192 66
1193 58
1194 106
1195 109
1196 103
1197 109
1198 103
1199 108
1200 102
1201 63
1202 62
1203 100
1204 62
1205 104
1206 65
1207 103
1208 63
1209 67
1210 105
1211 64
1212 108
1213 66
1214 65
1215 108
1216 101
1217 65
1218 64
1219 106
1220 103
1221 106
1222 100
1223 61
1224 63
1225 111
1226 109
1227 62
1228 67
1229 105
1230 63
1231 111
1232 103
1233 63
1234 99
1235 64
1236 110
1237 62
1238 106
1239 101
1240 65
1241 67
1242 106
1243 65
1244 63
1245 109
1246 104
1247 66
1248 62
1249 109
1250 61
1251 66
1252 62
1253 106
1254 65
1255 106
1256 104
1257 64
1258 104
1259 107
1260 103
1261 109
1262 61
1263 110
1264 65
1265 63
1266 64
1267 104
1268 109
1269 106
1270 64
1271 105
1272 99
1273 108
1274 109
1275 105
1276 99
1277 67
1278 106
1279 107
1280 60
1281 105
1282 101
1283 105
1284 59
1285 101
1286 62
1287 104
1288 60
1289 64
1290 63
1291 63
1292 65
1293 65
1294 107
1295 103
1296 63
1297 111
1298 105
1299 104
1300 62
1301 109
1302 107
1303 106
1304 63
1305 107
1306 61
1307 62
1308 109
1309 66
1310 104
1311 62
1312 62
1313 59
1314 62
1315 61
1316 64
1317 66
1318 64
1319 110
1320 65
1321 64
1322 106
1323 102
1324 63
1325 63
1326 103
1327 108
1328 110
1329 111
1330 64
1331 64
1332 56
1333 102
1334 60
1335 105
1336 61
1337 102
1338 65
1339 65
1340 106
1341 65
1342 63
1343 106
1344 62
1345 108
1346 62
1347 106
1348 100
1349 108
1350 101
1351 108
1352 62
1353 104
1354 107
1355 63
1356 107
1357 110
1358 106
1359 107
1360 63
1361 105
1362 103
1363 60
1364 64
1365 111
1366 63
1367 113
1368 62
1369 64
1370 66
1371 66
1372 66
1373 62
1374 101
1375 104
1376 101
1377 107
1378 107
1379 62
1380 63
1381 64
1382 63
1383 99
1384 101
1385 62
1386 102
1387 66
1388 61
1389 110
1390 110
1391 64
1392 104
1393 104
1394 60
1395 62
1396 60
1397 105
1398 110
1399 106
1400 109
1401 105
1402 99
1403 106
1404 105
1405 64
1406 101
1407 102
1408 65
1409 63
1410 106
1411 99
1412 62
1413 64
1414 64
1415 108
1416 104
1417 111
1418 66
1419 54
1420 64
1421 63
1422 105
1423 110
1424 67
1425 107
1426 63
1427 105
1428 64
1429 107
1430 104
1431 100
1432 61
1433 63
1434 107
1435 61
1436 110
1437 62
1438 106
1439 65
1440 63
1441 103
1442 63
1443 65
1444 63
1445 63
1446 103
1447 104
1448 60
1449 65
1450 60
1451 63
1452 57
1453 111
1454 67
1455 103
1456 108
1457 58
1458 106
1459 105
1460 62
1461 104
1462 62
1463 106
1464 101
1465 63
1466 62
1467 103
1468 63
1469 62
1470 101
1471 65
1472 103
1473 106
1474 102
1475 113
1476 107
1477 106
1478 108
1479 108
1480 59
1481 65
1482 106
1483 65
1484 64
1485 61
1486 106
1487 103
1488 62
1489 61
1490 107
1491 105
1492 103
1493 60
1494 63
1495 106
1496 64
1497 109
1498 67
1499 102
1500 66
1501 57
1502 63
1503 59
1504 107
1505 106
1506 100
1507 64
1508 58
1509 65
1510 62
1511 102
1512 108
1513 63
1514 104
1515 64
1516 62
1517 62
1518 61
1519 69
1520 106
1521 62
1522 64
1523 107
1524 63
1525 63
1526 62
1527 64
1528 63
1529 106
1530 102
1531 104
1532 63
1533 103
1534 64
1535 64
1536 106
1537 105
1538 99
1539 108
1540 62
1541 113
1542 107
1543 102
1544 61
1545 59
1546 103
1547 66
1548 65
1549 106
1550 59
1551 60
1552 63
1553 105
1554 109
1555 110
1556 57
1557 65
1558 103
1559 103
1560 61
1561 103
1562 102
1563 57
1564 64
1565 61
1566 63
1567 107
1568 62
1569 63
1570 106
1571 64
1572 62
1573 107
1574 105
1575 103
1576 63
1577 110
1578 67
1579 103
1580 106
1581 111
1582 65
1583 102
1584 107
1585 64
1586 60
1587 96
1588 107
1589 109
1590 65
1591 108
1592 64
1593 108
1594 65
1595 106
1596 103
1597 65
1598 105
1599 62
1600 66
1601 106
1602 61
1603 111
1604 106
1605 64
1606 107
1607 63
1608 63
1609 63
1610 63
1611 107
1612 105
1613 62
1614 106
1615 66
1616 107
1617 63
1618 107
1619 65
1620 62
1621 111
1622 106
1623 63
1624 102
1625 103
1626 63
1627 63
1628 62
1629 64
1630 62
1631 104
1632 104
1633 65
1634 58
1635 67
1636 66
1637 109
1638 103
1639 64
1640 105
1641 63
1642 105
1643 106
1644 109
1645 63
1646 108
1647 105
1648 63
1649 62
1650 106
1651 61
1652 64
1653 60
1654 108
1655 104
1656 102
1657 106
1658 105
1659 64
1660 61
1661 63
1662 65
1663 98
1664 68
1665 100
1666 104
1667 106
1668 101
1669 63
1670 111
1671 62
1672 62
1673 101
1674 103
1675 63
1676 63
1677 62
1678 105
1679 106
1680 63
1681 60
1682 105
1683 63
1684 105
1685 66
1686 107
1687 66
1688 66
1689 111
1690 63
1691 65
1692 101
1693 63
1694 111
1695 102
1696 103
1697 106
1698 105
1699 67
1700 63
1701 64
1702 107
1703 108
1704 61
1705 107
1706 62
1707 108
1708 106
1709 108
1710 61
1711 63
1712 62
1713 63
1714 62
1715 107
1716 106
1717 64
1718 63
1719 65
1720 103
1721 104
1722 109
1723 63
1724 66
1725 65
1726 104
1727 60
1728 64
1729 103
1730 102
1731 63
1732 64
1733 63
1734 63
1735 63
1736 102
1737 106
1738 64
1739 61
1740 65
1741 61
1742 109
1743 60
1744 107
1745 106
1746 68
1747 65
1748 104
1749 110
1750 102
1751 69
1752 60
1753 109
1754 109
1755 62
1756 66
1757 62
1758 65
1759 63
1760 107
1761 61
1762 63
1763 64
1764 105
1765 67
1766 106
1767 62
1768 108
1769 69
1770 60
1771 108
1772 64
1773 106
1774 64
1775 67
1776 109
1777 105
1778 106
1779 62
1780 108
1781 101
1782 108
1783 64
1784 64
1785 58
1786 106
1787 106
1788 105
1789 64
1790 108
1791 63
1792 105
1793 65
1794 108
1795 105
1796 103
1797 104
1798 63
1799 65
1800 63
1801 63
1802 64
1803 61
1804 63
1805 98
1806 64
1807 109
1808 106
1809 104
1810 62
1811 60
1812 110
1813 108
1814 62
1815 105
1816 63
1817 112
1818 63
1819 107
1820 64
1821 65
1822 64
1823 63
1824 105
1825 65
1826 63
1827 58
1828 63
1829 63
1830 101
1831 63
1832 108
1833 107
1834 101
1835 64
1836 103
1837 64
1838 62
1839 65
1840 62
1841 66
1842 107
1843 105
1844 60
1845 105
1846 62
1847 109
1848 110
1849 99
1850 106
1851 64
1852 106
1853 99
1854 64
1855 63
1856 60
1857 63
1858 67
1859 65
1860 109
1861 108
1862 64
1863 103
1864 65
1865 62
1866 107
1867 64
1868 62
1869 101
1870 105
1871 106
1872 110
1873 103
1874 66
1875 107
1876 60
1877 62
1878 106
1879 64
1880 99
1881 65
1882 101
1883 63
1884 64
1885 62
1886 64
1887 104
1888 61
1889 103
1890 103
1891 108
1892 103
1893 110
1894 110
1895 104
1896 104
1897 106
1898 108
1899 66
1900 68
1901 102
1902 65
1903 64
1904 67
1905 102
1906 63
1907 108
1908 105
1909 108
1910 62
1911 63
1912 107
1913 63
1914 65
1915 63
1916 107
1917 107
1918 102
1919 65
1920 107
1921 104
1922 107
1923 103
1924 62
1925 101
1926 63
1927 62
1928 64
1929 108
1930 103
1931 104
1932 65
1933 109
1934 64
1935 94
1936 60
1937 108
1938 101
1939 67
1940 66
1941 105
1942 64
1943 108
1944 106
1945 104
1946 105
1947 106
1948 114
1949 106
1950 63
1951 63
1952 65
1953 104
1954 107
1955 65
1956 61
1957 65
1958 60
1959 109
1960 106
1961 65
1962 104
1963 66
1964 106
1965 106
1966 66
1967 103
1968 106
1969 105
1970 63
1971 104
1972 101
1973 63
1974 62
1975 104
1976 63
1977 62
1978 109
1979 63
1980 103
1981 100
1982 64
1983 106
1984 61
1985 67
1986 62
1987 65
1988 101
1989 65
1990 64
1991 104
1992 107
1993 61
1994 105
1995 62
1996 63
1997 108
1998 62
1999 65
2000 217
2001 144
2002 294
2003 83
2004 207
2005 306
2006 75
2007 149
2008 123
2009 300
2010 300
2011 160
2012 160
2013 320
2014 252
2015 336
2016 191
2017 188
2018 173
2019 328
2020 321
2021 238
2022 318
2023 322
2024 304
2025 255
2026 205
2027 284
2028 319
2029 190
2030 324
2031 279
2032 302
2033 164
2034 105
2035 251
2036 206
2037 184
2038 72
2039 162
2040 289
2041 290
2042 311
2043 313
2044 235
2045 137
2046 315
2047 29
2048 134
2049 141
2050 307
2051 56
2052 317
2053 315
2054 298
2055 210
2056 229
2057 191
2058 307
2059 219
2060 90
2061 324
2062 305
2063 303
2064 80
2065 307
2066 336
2067 297
2068 266
2069 312
2070 270
2071 177
2072 311
2073 313
2074 238
2075 327
2076 307
2077 267
2078 282
2079 291
2080 217
2081 257
2082 341
2083 293
2084 314
2085 287
2086 319
2087 207
2088 171
2089 117
2090 182
2091 291
2092 281
2093 308
2094 164
2095 302
2096 306
2097 313
2098 234
2099 308
2100 291
2101 235
2102 314
2103 328
2104 189
2105 303
2106 225
2107 216
2108 240
2109 57
2110 266
2111 304
2112 271
2113 305
2114 200
2115 315
2116 292
2117 184
2118 109
2119 238
2120 295
2121 193
2122 247
2123 112
2124 250
2125 323
2126 298
2127 289
2128 92
2129 209
2130 293
2131 335
2132 169
2133 294
2134 247
2135 265
2136 161
2137 180
2138 295
2139 327
2140 305
2141 186
2142 255
2143 146
2144 120
2145 244
2146 302
2147 129
2148 266
2149 246
2150 305
2151 327
2152 173
2153 331
2154 329
2155 237
2156 281
2157 201
2158 258
2159 295
2160 205
2161 254
2162 255
2163 110
2164 339
2165 60
2166 238
2167 327
2168 332
2169 148
2170 199
2171 238
2172 245
2173 233
2174 313
2175 308
2176 156
2177 325
2178 196
2179 237

2180 193
2181 293
2182 146
2183 290
2184 207
2185 169
2186 103
2187 287
2188 276
2189 339
2190 259
2191 320
2192 232
2193 237
2194 328
2195 52
2196 201
2197 311
2198 235
2199 73
2200 302
2201 285
2202 235
2203 294
2204 308
2205 288
2206 316
2207 146
2208 296
2209 259
2210 228
2211 308
2212 131
2213 226
2214 219
2215 236
2216 30
2217 308
2218 172
2219 191
2220 308
2221 334
2222 332
2223 103
2224 320
2225 75
2226 272
2227 273
2228 140
2229 252
2230 310
2231 201
2232 232
2233 254
2234 309
2235 268
2236 326
2237 187
2238 310
2239 133
2240 181
2241 306
2242 218
2243 259
2244 132
2245 305
2246 292
2247 324
2248 225
2249 305
2250 266
2251 124
2252 325
2253 320
2254 199
2255 325
2256 308
2257 274
2258 313
2259 287
2260 282
2261 257
2262 279
2263 241
2264 187
2265 321
2266 284
2267 299
2268 182
2269 277
2270 315
2271 78
2272 160
2273 336
2274 334
2275 200
2276 332
2277 193
2278 314
2279 316
2280 296
2281 233
2282 311
2283 302
2284 149
2285 307
2286 44
2287 244
2288 203
2289 338
2290 319
2291 254
2292 210
2293 127
2294 336
2295 130
2296 224
2297 267
2298 313
2299 201
2300 238
2301 314
2302 326
2303 97
2304 306
2305 327
2306 233
2307 298
2308 168
2309 232
2310 193
2311 314
2312 252
2313 316
2314 244
2315 206
2316 74
2317 190
2318 107
2319 81
2320 311
2321 295
2322 200
2323 234
2324 304
2325 132
2326 290
2327 193
2328 322
2329 280
2330 290
2331 303
2332 287
2333 111
2334 168
2335 190
2336 173
2337 287
2338 273
2339 136
2340 336
2341 331
2342 333
2343 164
2344 299
2345 169
2346 313
2347 326
2348 80
2349 242
2350 326
2351 267
2352 332
2353 223
2354 281
2355 155
2356 76
2357 279
2358 186
2359 191
2360 226
2361 266
2362 281
2363 295
2364 183
2365 320
2366 325
2367 335
2368 235
2369 284
2370 279
2371 288
2372 286
2373 324
2374 153
2375 111
2376 147
2377 149
2378 82
2379 276
2380 341
2381 325
2382 297
2383 295
2384 178
2385 108
2386 310
2387 311
2388 302
2389 211
2390 234
2391 220
2392 291
2393 327
2394 309
2395 263
2396 201
2397 269
2398 317
2399 224

In [ ]:
set([1,2,3]) & set([])

In [ ]:
for i in range(len(cluster)):
    for j in range(len(cluster)):
        if len(set(cluster[j]) & set(cluster[i]))>0 and i !=j:
            cluster[i]=list(set(cluster[i]) | set(cluster[j]))
            cluster[j]=list()

In [ ]:
cluster1=dict()
i=0
for row in coreDist:
    cluster1[i]=np.where(row<eps)[0]
    i+=1

In [ ]:
for i in range(len(cluster1)):
    for j in range(len(cluster1)):
        if len(set(cluster1[j]).intersection(set(cluster1[i])))>0 and i !=j:
            cluster1[i]=list(set(cluster1[i]).union(set(cluster1[j])))
            cluster1[j]=list()

In [ ]:
cluster

In [ ]:
cluster1

In [ ]:
result=dict()
j=0
for i in range(len(cluster)):
    if len(cluster[i])>0:
        result[j]=cluster[i]
        j=j+1

In [ ]:
result

In [ ]:
for k,v in result.items():
    print(k,len(v))

In [ ]:
clrs=dict()
for i in range(len(result)):
    for j in result[i]:
        clrs[j]=i

In [ ]:
len(clrs)

In [ ]:
clrs

In [ ]:
sorted(clrs.items(),key=lambda x:x[0])

In [ ]:
clrs1=sorted(clrs.items(),key=lambda x:x[0])

In [ ]:
clrs2=[y for (x,y) in clrs1]

In [ ]:
clrs2

In [ ]:
len(clrs)

In [ ]:
clrs[1]

In [ ]:
clrs3=[]
for i in range(len(X)):
    clrs3.append(clrs[i])

In [ ]:
clrs3

In [ ]:
plt.scatter(X[:,0],X[:,1],c=clrs2)
plt.show()

In [ ]:
np.random.rand(10)

In [ ]:
X.shape