In [1]:
import numpy as np
import pandas as pd

In [2]:
df_train=pd.read_csv('F:\\study\\ml\\DataSet\\Tap4fun\\tap_fun_train.csv')

In [3]:
df_train.info(memory_usage='deep')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2288007 entries, 0 to 2288006
Columns: 109 entries, user_id to prediction_pay_price
dtypes: float64(13), int64(95), object(1)
memory usage: 2.0 GB

In [4]:
c_int=df_train.select_dtypes(include=['int64']).apply(pd.to_numeric,downcast='unsigned')
c_float=df_train.select_dtypes(include=['float']).apply(pd.to_numeric,downcast='float')

In [5]:
o_df=pd.concat([c_int,c_float],axis=1)

In [6]:
column_type=dict(o_df.dtypes.copy())

In [7]:
len(column_type)

108

In [8]:
del o_df,c_int,c_float,df_train

In [9]:
data_train=pd.read_csv('F:\\study\\ml\\DataSet\\Tap4fun\\tap_fun_train.csv',
                      dtype=column_type,parse_dates=['register_time'],infer_datetime_format=True)

In [10]:
data_train.rename(columns={'treatment_acceleraion_add_value':'treatment_acceleration_add_value',\
                          'sr_rss_a_prod_levell':'sr_rss_a_prod_level'} ,inplace=True)

In [11]:
data_train.head()

,user_id,register_time,wood_add_value,wood_reduce_value,stone_add_value,stone_reduce_value,ivory_add_value,ivory_reduce_value,meat_add_value,meat_reduce_value,...,pvp_battle_count,pvp_lanch_count,pvp_win_count,pve_battle_count,pve_lanch_count,pve_win_count,avg_online_minutes,pay_price,pay_count,prediction_pay_price
0,1,2018-02-02 19:47:15,20125.0,3700.0,0.0,0.0,0.0,0.0,16375.0,2000.0,...,0,0,0,0,0,0,0.333333,0.0,0,0.0
1,1593,2018-01-26 00:01:05,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,0.333333,0.0,0,0.0
2,1594,2018-01-26 00:01:58,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,1.166667,0.0,0,0.0
3,1595,2018-01-26 00:02:13,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,3.166667,0.0,0,0.0
4,1596,2018-01-26 00:02:46,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,2.333333,0.0,0,0.0

In [12]:
data_train.info(memory_usage='deep')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2288007 entries, 0 to 2288006
Columns: 109 entries, user_id to prediction_pay_price
dtypes: datetime64[ns](1), float32(13), uint16(8), uint32(21), uint8(66)
memory usage: 493.1 MB

In [13]:
data_label=data_train['prediction_pay_price']
data_train2=data_train.drop(labels=['user_id','register_time'],axis=1)

In [14]:
data_train2[(data_train2['pay_price']>0) & (data_train2['prediction_pay_price']>0)].shape

(41439, 107)

In [15]:
data_train2[(data_train2['pay_price']==0) & (data_train2['prediction_pay_price']>0)].shape

(4549, 107)

In [16]:
data_train2[(data_train2['pay_price']>0) & (data_train2['prediction_pay_price']==0)].shape

(0, 107)

In [17]:
data_train2[(data_train2['pay_price']>0)].shape

(41439, 107)

In [18]:
data_train2[(data_train2['prediction_pay_price']>0)].shape

(45988, 107)

In [19]:
data_train2[data_train2['prediction_pay_price']>0]['prediction_pay_price'].describe()

count    45988.000000
mean        89.228508
std        617.739014
min          0.990000
25%          0.990000
50%          3.970000
75%         20.980000
max      32977.808594
Name: prediction_pay_price, dtype: float64

In [20]:
# data_train2['price_per_count_qua1']=data_train2.pay_price / data_train2.pay_count
# del data_train2['price_per_count_qua1']

In [21]:
data_pay_7=data_train2[data_train2['pay_price']>0]
data_pay_45=data_train2[data_train2['prediction_pay_price']>0]

In [22]:
data_train2[(data_train2['pay_price']>0) & (data_train2['pay_price'] == data_train2['prediction_pay_price'])] \
[['pay_price','prediction_pay_price','avg_online_minutes',]].describe()
#pp> == ppp 只给了7天

          pay_price  prediction_pay_price  avg_online_minutes
count  30130.000000          30130.000000        30130.000000
mean      11.407172             11.407172          100.656929
std       71.140594             71.140594          113.973495
min        0.990000              0.990000            0.000000
25%        0.990000              0.990000           23.333332
50%        1.980000              1.980000           61.166668
75%        5.980000              5.980000          137.166672
max     4086.520020           4086.520020         1394.666626

In [23]:
data_train2[(data_train2['pay_price']>0) & (data_train2['pay_price'] < data_train2['prediction_pay_price'])] \
[['pay_price','prediction_pay_price','avg_online_minutes']].describe()
#pp>0 and pp< ppp 只给了7天,45天也付了

          pay_price  prediction_pay_price  avg_online_minutes
count  11309.000000          11309.000000        11309.000000
mean      77.782753            315.976807          245.507996
std      289.611267           1202.829590          180.424377
min        0.990000              1.980000            0.666667
25%        2.980000             16.940001          109.666664
50%       15.970000             48.919998          200.500000
75%       45.939999            163.759995          339.833344
max     7457.950195          32977.808594         1674.666626

In [24]:
data_train2[(data_train2['pay_price']==0) & (data_train2['prediction_pay_price']>0)] \
[['pay_price','prediction_pay_price','avg_online_minutes','general_acceleration_add_value']].describe()
#pp=0 and ppp>0 前7天未付款,后45天也付钱的

,pay_price,prediction_pay_price,avg_online_minutes,general_acceleration_add_value
count,4549.0,4549.000000,4549.000000,4549.000000
mean,0.0,40.842228,115.475998,2315.558804
std,0.0,238.763504,128.285599,2406.838272
min,0.0,0.990000,0.000000,0.000000
25%,0.0,0.990000,22.833332,543.000000
50%,0.0,5.980000,77.500000,1678.000000
75%,0.0,19.950001,159.166672,3414.000000
max,0.0,6752.970215,1098.833374,28764.000000

In [25]:
data_train2[(data_train2['pay_price']==0) & (data_train2['prediction_pay_price']==0)] \
[['pay_price','prediction_pay_price','avg_online_minutes','general_acceleration_add_value']].describe()

,pay_price,prediction_pay_price,avg_online_minutes,general_acceleration_add_value
count,2242019.0,2242019.0,2.242019e+06,2.242019e+06
mean,0.0,0.0,7.573942e+00,1.462377e+02
std,0.0,0.0,2.734151e+01,5.413398e+02
min,0.0,0.0,0.000000e+00,0.000000e+00
25%,0.0,0.0,5.000000e-01,0.000000e+00
50%,0.0,0.0,1.833333e+00,0.000000e+00
75%,0.0,0.0,4.500000e+00,5.000000e+01
max,0.0,0.0,2.049667e+03,5.786900e+04

In [26]:
data_train2[(data_train2['pay_price']>0) ] \
[['pay_price','prediction_pay_price','avg_online_minutes','pay_count']].describe()

          pay_price  prediction_pay_price  avg_online_minutes     pay_count
count  41439.000000          41439.000000        41439.000000  41439.000000
mean      29.528141             94.538071          140.187607      3.186226
std      165.658875            645.717285          149.972549      4.218311
min        0.990000              0.990000            0.000000      1.000000
25%        0.990000              0.990000           33.000000      1.000000
50%        1.990000              3.970000           88.833336      2.000000
75%       11.970000             21.950001          194.666672      4.000000
max     7457.950195          32977.808594         1674.666626    105.000000

In [27]:
data_train2[(data_train2['pay_price']>0) & (data_train2['pay_price'] < data_train2['prediction_pay_price'])] \
[['pay_price','prediction_pay_price','avg_online_minutes','pay_count']].describe()

          pay_price  prediction_pay_price  avg_online_minutes     pay_count
count  11309.000000          11309.000000        11309.000000  11309.000000
mean      77.782753            315.976807          245.507996      5.707932
std      289.611267           1202.829590          180.424377      6.470337
min        0.990000              1.980000            0.666667      1.000000
25%        2.980000             16.940001          109.666664      2.000000
50%       15.970000             48.919998          200.500000      4.000000
75%       45.939999            163.759995          339.833344      7.000000
max     7457.950195          32977.808594         1674.666626    105.000000

In [28]:
data_train2[(data_train2['pay_price']>0) & ( data_train2['prediction_pay_price'] == data_train2['pay_price'])] \
[['pay_price','prediction_pay_price','avg_online_minutes','pay_count']].describe()

          pay_price  prediction_pay_price  avg_online_minutes     pay_count
count  30130.000000          30130.000000        30130.000000  30130.000000
mean      11.407172             11.407172          100.656929      2.239728
std       71.140594             71.140594          113.973495      2.340433
min        0.990000              0.990000            0.000000      1.000000
25%        0.990000              0.990000           23.333332      1.000000
50%        1.980000              1.980000           61.166668      1.000000
75%        5.980000              5.980000          137.166672      3.000000
max     4086.520020           4086.520020         1394.666626     54.000000

In [29]:
data_7pay=data_train2[data_train2['pay_price']>0].copy()

In [30]:
data_7pay.head()

,wood_add_value,wood_reduce_value,stone_add_value,stone_reduce_value,ivory_add_value,ivory_reduce_value,meat_add_value,meat_reduce_value,magic_add_value,magic_reduce_value,...,pvp_battle_count,pvp_lanch_count,pvp_win_count,pve_battle_count,pve_lanch_count,pve_win_count,avg_online_minutes,pay_price,pay_count,prediction_pay_price
25,30000.0,97200.0,20000.0,0.0,0.0,0.0,160500.0,80392.0,12000.0,0.0,...,0,0,0,0,0,0,44.666668,0.99,1,0.99
40,1111744.0,1137687.0,491331.0,790208.0,77000.0,0.0,1457249.0,708483.0,217455.0,162987.0,...,1,1,1,6,6,6,199.333328,2.97,3,4.96
47,249050.0,173248.0,70841.0,117012.0,55000.0,0.0,206366.0,82205.0,29902.0,88064.0,...,0,0,0,0,0,0,109.333336,12.97,3,12.97
86,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,127.833336,0.99,1,0.99
119,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,203.166672,0.99,1,0.99

In [31]:
for name in data_7pay.columns.values:
    if 'add_value' in name:
        print(name+'-->'+name[:len(name)-10])
print('------------------')        
for name in data_7pay.columns.values:
    if 'reduce_value' in name:
        print(name+'-->'+name[:len(name)-10])

wood_add_value-->wood
stone_add_value-->stone
ivory_add_value-->ivory
meat_add_value-->meat
magic_add_value-->magic
infantry_add_value-->infantry
cavalry_add_value-->cavalry
shaman_add_value-->shaman
wound_infantry_add_value-->wound_infantry
wound_cavalry_add_value-->wound_cavalry
wound_shaman_add_value-->wound_shaman
general_acceleration_add_value-->general_acceleration
building_acceleration_add_value-->building_acceleration
reaserch_acceleration_add_value-->reaserch_acceleration
training_acceleration_add_value-->training_acceleration
treatment_acceleration_add_value-->treatment_acceleration
------------------
wood_reduce_value-->wood_re
stone_reduce_value-->stone_re
ivory_reduce_value-->ivory_re
meat_reduce_value-->meat_re
magic_reduce_value-->magic_re
infantry_reduce_value-->infantry_re
cavalry_reduce_value-->cavalry_re
shaman_reduce_value-->shaman_re
wound_infantry_reduce_value-->wound_infantry_re
wound_cavalry_reduce_value-->wound_cavalry_re
wound_shaman_reduce_value-->wound_shaman_re
general_acceleration_reduce_value-->general_acceleration_re
building_acceleration_reduce_value-->building_acceleration_re
reaserch_acceleration_reduce_value-->reaserch_acceleration_re
training_acceleration_reduce_value-->training_acceleration_re
treatment_acceleration_reduce_value-->treatment_acceleration_re

In [32]:
sum_delta_text=[]
sum_delta_text=['wood','stone']
for name in data_7pay.columns.values:
    if 'add_value' in name:
        sum_delta_text.append(name[:len(name)-10])
        
for i in sum_delta_text:
#     print(i+'_add_value  <--> '+i+'_reduce_value')
    add_name=i+'_add_value'
    reduce_name=i+'_reduce_value'
    sum_name=i+'_sum_qua1'
    delta_name=i+'_delta_qua2'
    print(add_name+' -- '+reduce_name)
#     print(reduce_name)
#     print(sum_name)
#     print(delta_name)
    data_7pay[sum_name]=data_7pay[add_name]+data_7pay[reduce_name]
    data_7pay[delta_name]=data_7pay[add_name]-data_7pay[reduce_name]
#     for k in range(3):
#         print('------------------{}--------------'.format(k))
#         print(data_7pay[add_name].iloc[k])
#         print(data_7pay[reduce_name].iloc[k])
#         print(data_7pay[add_name].iloc[k]-data_7pay[reduce_name].iloc[k])

wood_add_value -- wood_reduce_value
stone_add_value -- stone_reduce_value
wood_add_value -- wood_reduce_value
stone_add_value -- stone_reduce_value
ivory_add_value -- ivory_reduce_value
meat_add_value -- meat_reduce_value
magic_add_value -- magic_reduce_value
infantry_add_value -- infantry_reduce_value
cavalry_add_value -- cavalry_reduce_value
shaman_add_value -- shaman_reduce_value
wound_infantry_add_value -- wound_infantry_reduce_value
wound_cavalry_add_value -- wound_cavalry_reduce_value
wound_shaman_add_value -- wound_shaman_reduce_value
general_acceleration_add_value -- general_acceleration_reduce_value
building_acceleration_add_value -- building_acceleration_reduce_value
reaserch_acceleration_add_value -- reaserch_acceleration_reduce_value
training_acceleration_add_value -- training_acceleration_reduce_value
treatment_acceleration_add_value -- treatment_acceleration_reduce_value

In [33]:
data_7pay.head()

,wood_add_value,wood_reduce_value,stone_add_value,stone_reduce_value,ivory_add_value,ivory_reduce_value,meat_add_value,meat_reduce_value,magic_add_value,magic_reduce_value,...,general_acceleration_sum_qua1,general_acceleration_delta_qua2,building_acceleration_sum_qua1,building_acceleration_delta_qua2,reaserch_acceleration_sum_qua1,reaserch_acceleration_delta_qua2,training_acceleration_sum_qua1,training_acceleration_delta_qua2,treatment_acceleration_sum_qua1,treatment_acceleration_delta_qua2
25,30000.0,97200.0,20000.0,0.0,0.0,0.0,160500.0,80392.0,12000.0,0.0,...,260,260,75,75,0,0,165,165,0,0
40,1111744.0,1137687.0,491331.0,790208.0,77000.0,0.0,1457249.0,708483.0,217455.0,162987.0,...,1731,721,1073,73,750,716,1210,26,6,6
47,249050.0,173248.0,70841.0,117012.0,55000.0,0.0,206366.0,82205.0,29902.0,88064.0,...,2050,4294966586,0,0,1118,4294967016,45,45,0,0
86,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,0
119,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,0

In [34]:
data_7pay.head()

,wood_add_value,wood_reduce_value,stone_add_value,stone_reduce_value,ivory_add_value,ivory_reduce_value,meat_add_value,meat_reduce_value,magic_add_value,magic_reduce_value,...,general_acceleration_sum_qua1,general_acceleration_delta_qua2,building_acceleration_sum_qua1,building_acceleration_delta_qua2,reaserch_acceleration_sum_qua1,reaserch_acceleration_delta_qua2,training_acceleration_sum_qua1,training_acceleration_delta_qua2,treatment_acceleration_sum_qua1,treatment_acceleration_delta_qua2
25,30000.0,97200.0,20000.0,0.0,0.0,0.0,160500.0,80392.0,12000.0,0.0,...,260,260,75,75,0,0,165,165,0,0
40,1111744.0,1137687.0,491331.0,790208.0,77000.0,0.0,1457249.0,708483.0,217455.0,162987.0,...,1731,721,1073,73,750,716,1210,26,6,6
47,249050.0,173248.0,70841.0,117012.0,55000.0,0.0,206366.0,82205.0,29902.0,88064.0,...,2050,4294966586,0,0,1118,4294967016,45,45,0,0
86,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,0
119,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,0

In [35]:
data_7pay['wood_sum_qua1'].head()

25      127200.0
40     2249431.0
47      422298.0
86           0.0
119          0.0
Name: wood_sum_qua1, dtype: float32

In [36]:
data_7pay['wood_delta_qua2'].head()

25    -67200.0
40    -25943.0
47     75802.0
86         0.0
119        0.0
Name: wood_delta_qua2, dtype: float32

In [37]:
data_7pay.isna().sum().sum()

0

In [38]:
abs(-123.2)

123.2

In [39]:
delta_text=[]
for i in data_7pay.columns.values:
    if 'delta' in i:
        delta_text.append(i)
delta_text2=[]        
for k in delta_text:
    delta_text2.append(k[:len(k)-5]+'_abs_qua2')
print(delta_text2)

['wood_delta_abs_qua2', 'stone_delta_abs_qua2', 'ivory_delta_abs_qua2', 'meat_delta_abs_qua2', 'magic_delta_abs_qua2', 'infantry_delta_abs_qua2', 'cavalry_delta_abs_qua2', 'shaman_delta_abs_qua2', 'wound_infantry_delta_abs_qua2', 'wound_cavalry_delta_abs_qua2', 'wound_shaman_delta_abs_qua2', 'general_acceleration_delta_abs_qua2', 'building_acceleration_delta_abs_qua2', 'reaserch_acceleration_delta_abs_qua2', 'training_acceleration_delta_abs_qua2', 'treatment_acceleration_delta_abs_qua2']

In [40]:
data_7pay[delta_text2]=abs(data_7pay[delta_text])

In [41]:
data_7pay[delta_text].head()

,wood_delta_qua2,stone_delta_qua2,ivory_delta_qua2,meat_delta_qua2,magic_delta_qua2,infantry_delta_qua2,cavalry_delta_qua2,shaman_delta_qua2,wound_infantry_delta_qua2,wound_cavalry_delta_qua2,wound_shaman_delta_qua2,general_acceleration_delta_qua2,building_acceleration_delta_qua2,reaserch_acceleration_delta_qua2,training_acceleration_delta_qua2,treatment_acceleration_delta_qua2
25,-67200.0,20000.0,0.0,80108.0,12000.0,0,0,0,0,0,0,260,75,0,165,0
40,-25943.0,-298877.0,77000.0,748766.0,54468.0,60,4294967001,108,0,0,0,721,73,716,26,6
47,75802.0,-46171.0,55000.0,124161.0,-58162.0,0,0,0,0,0,0,4294966586,0,4294967016,45,0
86,0.0,0.0,0.0,0.0,0.0,0,0,0,0,0,0,0,0,0,0,0
119,0.0,0.0,0.0,0.0,0.0,0,0,0,0,0,0,0,0,0,0,0

In [42]:
data_7pay[delta_text2].head()

,wood_delta_abs_qua2,stone_delta_abs_qua2,ivory_delta_abs_qua2,meat_delta_abs_qua2,magic_delta_abs_qua2,infantry_delta_abs_qua2,cavalry_delta_abs_qua2,shaman_delta_abs_qua2,wound_infantry_delta_abs_qua2,wound_cavalry_delta_abs_qua2,wound_shaman_delta_abs_qua2,general_acceleration_delta_abs_qua2,building_acceleration_delta_abs_qua2,reaserch_acceleration_delta_abs_qua2,training_acceleration_delta_abs_qua2,treatment_acceleration_delta_abs_qua2
25,67200.0,20000.0,0.0,80108.0,12000.0,0.0,0.000000e+00,0.0,0.0,0.0,0.0,2.600000e+02,75.0,0.000000e+00,165.0,0.0
40,25943.0,298877.0,77000.0,748766.0,54468.0,60.0,4.294967e+09,108.0,0.0,0.0,0.0,7.210000e+02,73.0,7.160000e+02,26.0,6.0
47,75802.0,46171.0,55000.0,124161.0,58162.0,0.0,0.000000e+00,0.0,0.0,0.0,0.0,4.294967e+09,0.0,4.294967e+09,45.0,0.0
86,0.0,0.0,0.0,0.0,0.0,0.0,0.000000e+00,0.0,0.0,0.0,0.0,0.000000e+00,0.0,0.000000e+00,0.0,0.0
119,0.0,0.0,0.0,0.0,0.0,0.0,0.000000e+00,0.0,0.0,0.0,0.0,0.000000e+00,0.0,0.000000e+00,0.0,0.0

In [43]:
text_shaman=[]
for col in data_7pay.columns.values:
     if 'shaman' in col:
            text_shaman.append(col)
data_7pay[text_shaman]

,shaman_add_value,shaman_reduce_value,wound_shaman_add_value,wound_shaman_reduce_value,sr_shaman_tier_2_level,sr_shaman_atk_level,sr_shaman_tier_3_level,sr_shaman_def_level,sr_shaman_hp_level,sr_shaman_tier_4_level,shaman_sum_qua1,shaman_delta_qua2,wound_shaman_sum_qua1,wound_shaman_delta_qua2,shaman_delta_abs_qua2,wound_shaman_delta_abs_qua2
25,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.000000e+00,0.000000e+00
40,370,262,0,0,0,0,0,0,0,0,632,108,0,0,1.080000e+02,0.000000e+00
47,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.000000e+00,0.000000e+00
86,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.000000e+00,0.000000e+00
119,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.000000e+00,0.000000e+00
155,813,1534,0,288,0,4,0,0,0,0,2347,4294966575,288,4294967008,4.294967e+09,4.294967e+09
171,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.000000e+00,0.000000e+00
214,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.000000e+00,0.000000e+00
248,266,266,266,266,0,0,0,0,0,0,532,0,532,0,0.000000e+00,0.000000e+00
305,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.000000e+00,0.000000e+00
380,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.000000e+00,0.000000e+00
381,1864,220,220,244,0,4,0,0,0,0,2084,1644,464,4294967272,1.644000e+03,4.294967e+09
390,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.000000e+00,0.000000e+00
434,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.000000e+00,0.000000e+00
450,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.000000e+00,0.000000e+00
481,330,0,0,0,0,0,0,0,0,0,330,330,0,0,3.300000e+02,0.000000e+00
562,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.000000e+00,0.000000e+00
616,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.000000e+00,0.000000e+00
617,0,313,6,0,0,0,0,0,0,0,313,4294966983,6,6,4.294967e+09,6.000000e+00
625,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.000000e+00,0.000000e+00
630,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.000000e+00,0.000000e+00
643,0,27,27,0,1,1,0,0,0,0,27,4294967269,27,27,4.294967e+09,2.700000e+01
716,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.000000e+00,0.000000e+00
726,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.000000e+00,0.000000e+00
817,850,2,0,0,0,1,0,0,0,0,852,848,0,0,8.480000e+02,0.000000e+00
835,1375,2373,1375,1375,0,2,0,0,0,0,3748,4294966298,2750,0,4.294966e+09,0.000000e+00
845,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.000000e+00,0.000000e+00
981,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.000000e+00,0.000000e+00
982,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.000000e+00,0.000000e+00
1004,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.000000e+00,0.000000e+00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2286844,5945,6052,5590,5590,1,3,0,0,0,0,11997,4294967189,11180,0,4.294967e+09,0.000000e+00
2286871,25528,28732,25528,25528,1,5,0,0,0,0,54260,4294964092,51056,0,4.294964e+09,0.000000e+00
2286913,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0.000000e+00,0.000000e+00
2286961,1152,405,192,192,1,3,0,0,0,0,1557,747,384,0,7.470000e+02,0.000000e+00
2286987,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.000000e+00,0.000000e+00
2287028,1156,1177,766,766,0,0,0,0,0,0,2333,4294967275,1532,0,4.294967e+09,0.000000e+00
2287109,150,1601,0,0,1,0,0,0,0,0,1751,4294965845,0,0,4.294966e+09,0.000000e+00
2287140,3295,3100,3100,3100,1,0,0,0,0,0,6395,195,6200,0,1.950000e+02,0.000000e+00
2287179,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.000000e+00,0.000000e+00
2287262,6270,26,0,0,1,3,0,0,0,0,6296,6244,0,0,6.244000e+03,0.000000e+00
2287373,2691,4915,1971,1971,1,2,0,0,0,0,7606,4294965072,3942,0,4.294965e+09,0.000000e+00
2287410,585,1805,585,0,1,1,0,0,0,0,2390,4294966076,585,585,4.294966e+09,5.850000e+02
2287492,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.000000e+00,0.000000e+00
2287517,5440,847,2,0,1,0,0,0,0,0,6287,4593,2,2,4.593000e+03,2.000000e+00
2287520,877,5342,4252,182,1,1,0,0,0,0,6219,4294962831,4434,4070,4.294963e+09,4.070000e+03
2287555,1576,802,0,0,1,2,0,0,0,0,2378,774,0,0,7.740000e+02,0.000000e+00
2287618,10176,8609,3986,3986,1,2,0,0,0,0,18785,1567,7972,0,1.567000e+03,0.000000e+00
2287668,0,565,565,0,0,0,0,0,0,0,565,4294966731,565,565,4.294967e+09,5.650000e+02
2287708,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.000000e+00,0.000000e+00
2287712,13590,15087,13200,13200,0,0,0,0,0,0,28677,4294965799,26400,0,4.294966e+09,0.000000e+00
2287742,3696,2863,1751,1751,1,1,0,0,0,0,6559,833,3502,0,8.330000e+02,0.000000e+00
2287780,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.000000e+00,0.000000e+00
2287839,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.000000e+00,0.000000e+00
2287863,220,3382,0,0,1,1,0,0,0,0,3602,4294964134,0,0,4.294964e+09,0.000000e+00
2287876,19500,20261,17791,17791,1,4,0,0,0,0,39761,4294966535,35582,0,4.294967e+09,0.000000e+00
2287944,322,913,322,322,1,0,0,0,0,0,1235,4294966705,644,0,4.294967e+09,0.000000e+00
2287946,27110,14145,8126,7567,1,2,0,0,0,0,41255,12965,15693,559,1.296500e+04,5.590000e+02
2287960,221,824,221,221,1,0,0,0,0,0,1045,4294966693,442,0,4.294967e+09,0.000000e+00
2287970,500,1735,1407,310,0,0,0,0,0,0,2235,4294966061,1717,1097,4.294966e+09,1.097000e+03
2287984,0,100,99,0,0,0,0,0,0,0,100,4294967196,99,99,4.294967e+09,9.900000e+01

In [44]:
import re

In [45]:
re.findall(r'\d','sr_outpost_tier_3_level')

['3']

In [46]:
level1_text=[]
level2_text=[]
level3_text=[]
level4_text=[]
for i in data_7pay.columns.values:
    if 'level' in i:
        if re.findall(r'\d',i)==['2']:
            level2_text.append(i)
        elif re.findall(r'\d',i)==['3']:
            level3_text.append(i)
        elif re.findall(r'\d',i)==['4']:
            level4_text.append(i)
        else :
            level1_text.append(i)
print('-------------1 ----------')            
print(level1_text)
print('-------------2----------')            
print(level2_text)
print('-------------3 ----------')            
print(level3_text)
print('-------------4 ----------')            
print(level4_text)

-------------1 ----------
['bd_training_hut_level', 'bd_healing_lodge_level', 'bd_stronghold_level', 'bd_outpost_portal_level', 'bd_barrack_level', 'bd_healing_spring_level', 'bd_dolmen_level', 'bd_guest_cavern_level', 'bd_warehouse_level', 'bd_watchtower_level', 'bd_magic_coin_tree_level', 'bd_hall_of_war_level', 'bd_market_level', 'bd_hero_gacha_level', 'bd_hero_strengthen_level', 'bd_hero_pve_level', 'sr_scout_level', 'sr_training_speed_level', 'sr_infantry_atk_level', 'sr_cavalry_atk_level', 'sr_shaman_atk_level', 'sr_troop_defense_level', 'sr_infantry_def_level', 'sr_cavalry_def_level', 'sr_shaman_def_level', 'sr_infantry_hp_level', 'sr_cavalry_hp_level', 'sr_shaman_hp_level', 'sr_troop_attack_level', 'sr_construction_speed_level', 'sr_hide_storage_level', 'sr_troop_consumption_level', 'sr_rss_a_prod_level', 'sr_rss_b_prod_level', 'sr_rss_c_prod_level', 'sr_rss_d_prod_level', 'sr_rss_a_gather_level', 'sr_rss_b_gather_level', 'sr_rss_c_gather_level', 'sr_rss_d_gather_level', 'sr_troop_load_level', 'sr_rss_e_gather_level', 'sr_rss_e_prod_level', 'sr_outpost_durability_level', 'sr_healing_space_level', 'sr_gathering_hunter_buff_level', 'sr_healing_speed_level', 'sr_alliance_march_speed_level', 'sr_pvp_march_speed_level', 'sr_gathering_march_speed_level', 'sr_guest_troop_capacity_level', 'sr_march_size_level', 'sr_rss_help_bonus_level']
-------------2----------
['sr_infantry_tier_2_level', 'sr_cavalry_tier_2_level', 'sr_shaman_tier_2_level', 'sr_outpost_tier_2_level']
-------------3 ----------
['sr_infantry_tier_3_level', 'sr_cavalry_tier_3_level', 'sr_shaman_tier_3_level', 'sr_outpost_tier_3_level']
-------------4 ----------
['sr_infantry_tier_4_level', 'sr_cavalry_tier_4_level', 'sr_shaman_tier_4_level', 'sr_outpost_tier_4_level']

In [47]:
data_7pay[level1_text].head(30)

,bd_training_hut_level,bd_healing_lodge_level,bd_stronghold_level,bd_outpost_portal_level,bd_barrack_level,bd_healing_spring_level,bd_dolmen_level,bd_guest_cavern_level,bd_warehouse_level,bd_watchtower_level,...,sr_outpost_durability_level,sr_healing_space_level,sr_gathering_hunter_buff_level,sr_healing_speed_level,sr_alliance_march_speed_level,sr_pvp_march_speed_level,sr_gathering_march_speed_level,sr_guest_troop_capacity_level,sr_march_size_level,sr_rss_help_bonus_level
25,0,0,0,0,0,0,7,0,0,0,...,0,0,0,0,0,0,0,0,0,0
40,8,10,0,0,9,0,9,0,9,0,...,0,1,0,0,0,0,0,0,0,0
47,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
86,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
119,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
155,7,5,12,12,12,0,12,0,0,11,...,3,0,0,0,0,0,0,0,0,0
171,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
214,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
248,5,7,0,8,0,7,7,7,8,8,...,0,1,0,0,0,0,0,0,0,0
305,0,6,0,0,0,8,8,0,0,0,...,0,0,0,0,0,0,0,0,0,0
380,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
381,11,10,11,10,0,11,11,10,10,10,...,0,5,5,4,2,2,2,0,0,0
390,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
434,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
450,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
481,0,9,11,0,0,10,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
562,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
616,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
617,9,0,14,0,0,11,12,0,0,0,...,0,0,0,0,0,0,0,0,0,0
625,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
630,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
643,6,0,0,9,7,0,9,0,0,0,...,0,0,0,0,0,0,0,0,0,0
716,0,0,0,9,9,0,9,8,0,10,...,0,0,0,1,0,0,0,0,0,0
726,6,7,8,8,0,8,0,7,0,0,...,0,0,0,0,0,0,0,0,0,0
817,8,0,10,0,9,0,9,9,9,0,...,0,0,0,0,0,0,0,0,0,0
835,7,9,0,10,0,0,9,0,0,0,...,0,0,0,0,0,0,0,0,0,0
845,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
981,6,0,10,9,0,0,9,10,0,0,...,0,0,1,0,0,0,0,0,0,0
982,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1004,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [48]:
data_7pay[level2_text].head(30)

,sr_infantry_tier_2_level,sr_cavalry_tier_2_level,sr_shaman_tier_2_level,sr_outpost_tier_2_level
25,0,0,0,0
40,0,0,0,0
47,0,0,0,0
86,0,0,0,0
119,0,0,0,0
155,0,0,0,1
171,0,0,0,0
214,0,0,0,0
248,0,0,0,0
305,1,1,0,0
380,0,0,0,0
381,0,0,0,0
390,0,0,0,0
434,0,0,0,0
450,0,0,0,0
481,0,0,0,0
562,0,0,0,0
616,0,0,0,0
617,0,0,0,0
625,0,0,0,0
630,0,0,0,0
643,1,0,1,0
716,0,0,0,0
726,1,1,0,0
817,0,0,0,0
835,0,0,0,0
845,0,0,0,0
981,0,0,0,0
982,0,0,0,0
1004,0,0,0,0

In [49]:
data_7pay[level3_text].head(30)

,sr_infantry_tier_3_level,sr_cavalry_tier_3_level,sr_shaman_tier_3_level,sr_outpost_tier_3_level
25,0,0,0,0
40,0,0,0,0
47,0,0,0,0
86,0,0,0,0
119,0,0,0,0
155,0,0,0,0
171,0,0,0,0
214,0,0,0,0
248,0,0,0,0
305,0,0,0,0
380,0,0,0,0
381,0,0,0,1
390,0,0,0,0
434,0,0,0,0
450,0,0,0,0
481,0,0,0,0
562,0,0,0,0
616,0,0,0,0
617,0,0,0,0
625,0,0,0,0
630,0,0,0,0
643,0,0,0,0
716,0,0,0,0
726,0,0,0,0
817,0,0,0,0
835,0,0,0,0
845,0,0,0,0
981,0,0,0,0
982,0,0,0,0
1004,0,0,0,0

In [50]:
data_7pay[level4_text].head(30)

,sr_infantry_tier_4_level,sr_cavalry_tier_4_level,sr_shaman_tier_4_level,sr_outpost_tier_4_level
25,0,0,0,0
40,0,0,0,0
47,0,0,0,0
86,0,0,0,0
119,0,0,0,0
155,0,0,0,0
171,0,0,0,0
214,0,0,0,0
248,0,0,0,0
305,0,0,0,0
380,0,0,0,0
381,0,0,0,0
390,0,0,0,0
434,0,0,0,0
450,0,0,0,0
481,0,0,0,0
562,0,0,0,0
616,0,0,0,0
617,0,0,0,0
625,0,0,0,0
630,0,0,0,0
643,0,0,0,0
716,0,0,0,0
726,0,0,0,0
817,0,0,0,0
835,0,0,0,0
845,0,0,0,0
981,0,0,0,0
982,0,0,0,0
1004,0,0,0,0

In [51]:
for i in level1_text:
    if 'shaman' in i:
        print(i)

sr_shaman_atk_level
sr_shaman_def_level
sr_shaman_hp_level

In [52]:
infantry_text1=[]
cavalry_text1=[]
shaman_text1=[]
outpost_text1=[]
for i in level1_text:
    if 'infantry' in i:
        infantry_text1.append(i)
    elif 'cavalry' in i:
        cavalry_text1.append(i)
    elif 'shaman' in i:
        shaman_text1.append(i)
    elif 'outpost' in i:
        outpost_text1.append(i)

In [53]:
for i in shaman_text1:
    print(i)

sr_shaman_atk_level
sr_shaman_def_level
sr_shaman_hp_level

In [54]:
data_7pay['infantry_hp_atk_def_sum_qua1']=0
data_7pay['cavalry_hp_atk_def_sum_qua1']=0
data_7pay['shaman_hp_atk_def_sum_qua1']=0
data_7pay['outpost_hp_atk_def_sum_qua1']=0
for i in infantry_text1:
    name='infantry_hp_atk_def_sum_qua1'
    data_7pay[name]+=data_7pay[i]
for i in cavalry_text1:
    name='cavalry_hp_atk_def_sum_qua1'
    data_7pay[name]+=data_7pay[i]
for i in shaman_text1:
    name='shaman_hp_atk_def_sum_qua1'
    data_7pay[name]+=data_7pay[i]    
for i in outpost_text1:
    name='outpost_hp_atk_def_sum_qua1'
    data_7pay[name]+=data_7pay[i]

In [55]:
data_7pay['infantry_tier_2_sum_qua2']=0
data_7pay['cavalry_tier_2_sum_qua2']=0
data_7pay['shaman_tier_2_sum_qua2']=0
data_7pay['outpost_tier_2_sum_qua2']=0
infantry_text2=[]
cavalry_text2=[]
shaman_text2=[]
outpost_text2=[]
for i in level2_text:
    if 'infantry' in i:
        infantry_text2.append(i)
    elif 'cavalry' in i:
        cavalry_text2.append(i)
    elif 'shaman' in i:
        shaman_text2.append(i)
    elif 'outpost' in i:
        outpost_text2.append(i)
##############################################        
for i in infantry_text2:
    name='infantry_tier_2_sum_qua2'
    data_7pay[name]+=data_7pay[i]
for i in cavalry_text2:
    name='cavalry_tier_2_sum_qua2'
    data_7pay[name]+=data_7pay[i]
for i in shaman_text2:
    name='shaman_tier_2_sum_qua2'
    data_7pay[name]+=data_7pay[i]    
for i in outpost_text2:
    name='outpost_tier_2_sum_qua2'
    data_7pay[name]+=data_7pay[i]

In [56]:
data_7pay['infantry_tier_3_sum_qua3']=0
data_7pay['cavalry_tier_3_sum_qua3']=0
data_7pay['shaman_tier_3_sum_qua3']=0
data_7pay['outpost_tier_3_sum_qua3']=0
infantry_text3=[]
cavalry_text3=[]
shaman_text3=[]
outpost_text3=[]
for i in level3_text:
    if 'infantry' in i:
        infantry_text3.append(i)
    elif 'cavalry' in i:
        cavalry_text3.append(i)
    elif 'shaman' in i:
        shaman_text3.append(i)
    elif 'outpost' in i:
        outpost_text3.append(i)
##############################################        
for i in infantry_text3:
    name='infantry_tier_3_sum_qua3'
    data_7pay[name]+=data_7pay[i]
for i in cavalry_text3:
    name='cavalry_tier_3_sum_qua3'
    data_7pay[name]+=data_7pay[i]
for i in shaman_text3:
    name='shaman_tier_3_sum_qua3'
    data_7pay[name]+=data_7pay[i]    
for i in outpost_text3:
    name='outpost_tier_3_sum_qua3'
    data_7pay[name]+=data_7pay[i]

In [57]:
data_7pay['infantry_tier_4_sum_qua4']=0
data_7pay['cavalry_tier_4_sum_qua4']=0
data_7pay['shaman_tier_4_sum_qua4']=0
data_7pay['outpost_tier_4_sum_qua4']=0
infantry_text4=[]
cavalry_text4=[]
shaman_text4=[]
outpost_text4=[]
for i in level4_text:
    if 'infantry' in i:
        infantry_text4.append(i)
    elif 'cavalry' in i:
        cavalry_text4.append(i)
    elif 'shaman' in i:
        shaman_text4.append(i)
    elif 'outpost' in i:
        outpost_text4.append(i)
##############################################        
for i in infantry_text4:
    name='infantry_tier_4_sum_qua4'
    data_7pay[name]+=data_7pay[i]
for i in cavalry_text4:
    name='cavalry_tier_4_sum_qua4'
    data_7pay[name]+=data_7pay[i]
for i in shaman_text4:
    name='shaman_tier_4_sum_qua4'
    data_7pay[name]+=data_7pay[i]    
for i in outpost_text4:
    name='outpost_tier_4_sum_qua4'
    data_7pay[name]+=data_7pay[i]

In [58]:
rss_test=[]
for i in data_7pay.columns.values:
    if 'rss' in i:
        rss_test.append(i)
        print(i[:9])

sr_rss_a_
sr_rss_b_
sr_rss_c_
sr_rss_d_
sr_rss_a_
sr_rss_b_
sr_rss_c_
sr_rss_d_
sr_rss_e_
sr_rss_e_
sr_rss_he

In [59]:
for i in data_7pay.columns.values:
    if 'sr_rss_c' in i:
        print(i)

sr_rss_c_prod_level
sr_rss_c_gather_level

In [60]:
for i in rss_test:
    if 'prod' in i:
        col_name=i[:9]+'sum_qua1'
        prod_name=i[:9]+'prod_level'
        gather_name=i[:9]+'gather_level'
        data_7pay[col_name]=data_7pay[prod_name]+data_7pay[gather_name]

In [61]:
data_7pay.head()

,wood_add_value,wood_reduce_value,stone_add_value,stone_reduce_value,ivory_add_value,ivory_reduce_value,meat_add_value,meat_reduce_value,magic_add_value,magic_reduce_value,...,outpost_tier_3_sum_qua3,infantry_tier_4_sum_qua4,cavalry_tier_4_sum_qua4,shaman_tier_4_sum_qua4,outpost_tier_4_sum_qua4,sr_rss_a_sum_qua1,sr_rss_b_sum_qua1,sr_rss_c_sum_qua1,sr_rss_d_sum_qua1,sr_rss_e_sum_qua1
25,30000.0,97200.0,20000.0,0.0,0.0,0.0,160500.0,80392.0,12000.0,0.0,...,0,0,0,0,0,0,0,0,0,0
40,1111744.0,1137687.0,491331.0,790208.0,77000.0,0.0,1457249.0,708483.0,217455.0,162987.0,...,0,0,0,0,0,3,0,0,0,0
47,249050.0,173248.0,70841.0,117012.0,55000.0,0.0,206366.0,82205.0,29902.0,88064.0,...,0,0,0,0,0,3,0,0,0,0
86,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,0
119,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,0

In [64]:
for i ,k in data_train2[[i for i in level1_text ]].max().iteritems():
    print(k)

20
19
23
23
21
21
22
20
21
21
21
18
19
19
17
21
9
17
13
11
10
14
11
11
11
11
11
11
11
15
11
11
9
9
9
11
9
9
7
9
10
9
9
10
11
10
9
10
11
10
3
9
8

In [65]:
data_7pay[[i for i in level1_text ]].head()

,bd_training_hut_level,bd_healing_lodge_level,bd_stronghold_level,bd_outpost_portal_level,bd_barrack_level,bd_healing_spring_level,bd_dolmen_level,bd_guest_cavern_level,bd_warehouse_level,bd_watchtower_level,...,sr_outpost_durability_level,sr_healing_space_level,sr_gathering_hunter_buff_level,sr_healing_speed_level,sr_alliance_march_speed_level,sr_pvp_march_speed_level,sr_gathering_march_speed_level,sr_guest_troop_capacity_level,sr_march_size_level,sr_rss_help_bonus_level
25,0,0,0,0,0,0,7,0,0,0,...,0,0,0,0,0,0,0,0,0,0
40,8,10,0,0,9,0,9,0,9,0,...,0,1,0,0,0,0,0,0,0,0
47,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
86,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
119,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [67]:
data_7pay[[i for i in level4_text]].head()

,sr_infantry_tier_4_level,sr_cavalry_tier_4_level,sr_shaman_tier_4_level,sr_outpost_tier_4_level
25,0,0,0,0
40,0,0,0,0
47,0,0,0,0
86,0,0,0,0
119,0,0,0,0

In [75]:
data_7pay['sr_infantry_tier_2_level'].unique()

array([0, 1], dtype=uint64)

In [81]:
a=pd.DataFrame()
for i in level2_text:
    a=pd.concat([a,pd.get_dummies(data_7pay[i],prefix='du_'+i)],axis=1)

In [82]:
a.head()

,du_sr_infantry_tier_2_level_0,du_sr_infantry_tier_2_level_1,du_sr_cavalry_tier_2_level_0,du_sr_cavalry_tier_2_level_1,du_sr_shaman_tier_2_level_0,du_sr_shaman_tier_2_level_1,du_sr_outpost_tier_2_level_0,du_sr_outpost_tier_2_level_1
25,1,0,1,0,1,0,1,0
40,1,0,1,0,1,0,1,0
47,1,0,1,0,1,0,1,0
86,1,0,1,0,1,0,1,0
119,1,0,1,0,1,0,1,0

In [ ]:
# data_7pay['ivory_qua1']=data_7pay.ivory_add_value+data_7pay.ivory_reduce_value
# data_7pay['ivory_qua2']=data_7pay.ivory_add_value-data_7pay.ivory_reduce_value
# data_7pay['stone_qua1']=data_7pay.stone_add_value+data_7pay.stone_reduce_value
# data_7pay['stone_qua2']=data_7pay.stone_add_value-data_7pay.stone_reduce_value
# data_7pay['meat_qua1']=data_7pay.meat_add_value+data_7pay.meat_reduce_value
# data_7pay['meat_qua2']=data_7pay.meat_add_value-data_7pay.meat_reduce_value
# data_7pay['wood_qua1']=data_7pay.wood_add_value+data_7pay.wood_reduce_value
# data_7pay['wood_qua2']=data_7pay.wood_add_value-data_7pay.wood_reduce_value

text_def=[]
for col in data_7pay.columns.values:
     if 'def' in col:
            text_def.append(col)
text_def=[]
for col in data_7pay.columns.values:
     if 'def' in col:
            text_def.append(col)
text_troop=[]
for col in data_7pay.columns.values:
    if 'troop' in col :
        text_troop.append(col)
text_cavalry=[]
for col in data_7pay.columns.values:
    if 'sr_cavalry' in col :
        text_cavalry.append(col) 
text_infantry=[]
for col in data_7pay.columns.values:
    if 'sr_infantry' in col :
        text_infantry.append(col)        

text_shaman=[]
for col in data_7pay.columns.values:
    if 'sr_shaman' in col :
        text_shaman.append(col)
text_speed=[]
for col in data_7pay.columns.values:
    if 'speed' in col :
        text_speed.append(col)
data_7pay['def_qua1']=0.0
for name in text_def:
    data_7pay['def_qua1']+=data_7pay[name]
data_7pay['cavalry_qua1']=0.0
for name in text_cavalry:
    data_7pay['cavalry_qua1']+=data_7pay[name]
data_7pay['infantry_qua1']=0.0
for name in text_infantry:
    data_7pay['infantry_qua1']+=data_7pay[name] 
data_7pay['shaman_qua1']=0.0
for name in text_shaman:
    data_7pay['shaman_qua1']+=data_7pay[name]
data_7pay['speed_qua1']=0.0
for name in text_speed:
    data_7pay['speed_qua1']+=data_7pay[name]
data_7pay['troop_qua1']=0.0
for name in text_troop:
    data_7pay['troop_qua1']+=data_7pay[name]


text_acceleration=[]
for col in data_7pay.columns.values:
    if 'acceleration' in col :
        text_acceleration.append(col)
text_acceleration_add=[]
for col in data_7pay.columns.values:
    if 'acceleration_add' in col :
        text_acceleration_add.append(col)
text_acceleration_reduce=[]
for col in data_7pay.columns.values:
    if 'acceleration_reduce' in col :
        text_acceleration_reduce.append(col) 
        
data_7pay['acceleration_qua1']=0.0
for name in text_acceleration:
    data_7pay['acceleration_qua1']+=data_7pay[name]
data_7pay['acceleration_add_qua1']=0.0
for name in text_acceleration_add:
    data_7pay['acceleration_add_qua1']+=data_7pay[name]
data_7pay['acceleration_reduce_qua1']=0.0
for name in text_acceleration_reduce:
    data_7pay['acceleration_reduce_qua1']+=data_7pay[name]

In [ ]:
# data_7pay['price_per_count_qua1']=data_7pay['pay_price'] / data_7pay['pay_count']

In [ ]:
text_qua=[]
for col in data_7pay.columns.values:
    if 'qua' in col:
        text_qua.append(col)

In [ ]:
# data_7pay[(data_7pay['pay_price']>0) & ( data_7pay['prediction_pay_price'] == data_7pay['pay_price'])] \
# [['pay_price','prediction_pay_price','avg_online_minutes','pay_count','price_per_count_qua1']].describe()

In [ ]:
# data_7pay[(data_7pay['pay_price']>0) & ( data_7pay['prediction_pay_price'] > data_7pay['pay_price'])] \
# [['pay_price','prediction_pay_price','avg_online_minutes','pay_count','price_per_count_qua1']].describe()

In [ ]:
# for name in data_7pay.columns.values:
#     price_name=name+'_per_price_qua3'
#     data_7pay[price_name]=data_7pay[name] / data_7pay['pay_price']

In [ ]:
for name in data_7pay.columns.values:
    price_name=name+'_per_price_qua3'
    count_name=name+'_per_count_qua3'
    mean_name=name+'_price_count_mean_qua3'
    data_7pay[price_name]=data_7pay[name] / data_7pay['pay_price']
    data_7pay[count_name]=data_7pay[name] / data_7pay['pay_count']
    data_7pay[mean_name]=data_7pay[name] / (data_7pay['pay_price']/data_7pay['pay_count'])

In [ ]:
data_7pay.head()

In [ ]:
# text_qua3=[]
# for col in data_7pay.columns.values:
#     if 'qua3' in col:
#         text_qua3.append(col)
# data_7pay.drop(labels=text_qua3,axis=1,inplace=True)

In [ ]:
data_7pay.head()

In [ ]:
data_7pay_corr=data_7pay.corr()

In [ ]:
for name,value in data_7pay_corr['pay_price'].sort_values(ascending=False).iteritems():
    print('{:<50}{:>50}'.format(name,value))

In [ ]:
for name ,value in data_7pay_corr['prediction_pay_price'].sort_values(ascending=False).iteritems():
    print('{:<50}{:>50}'.format(name,value))

In [ ]:
data_7pay_corr.shape

In [ ]:
# data_pay_7_corr=data_pay_7.corr()

In [ ]:
# data_pay_7_corr['prediction_pay_price'].sort_values(ascending=False)

In [ ]:
# data_pay_45_corr=data_pay_45.corr()

In [ ]:
# data_pay_45_corr['prediction_pay_price'].sort_values(ascending=False)

In [ ]:
# data_7nopay=data_train2[(data_train2['pay_price']==0)]

# data_7nopay_corr=data_7nopay.corr()

# # data_7nopay_corr['prediction_pay_price'].sort_values(ascending=False)

# data_7nopay_45pay=data_train2[(data_train2['pay_price']==0) &  (data_train2['prediction_pay_price']>0)]

# data_7nopay_45pay_corr=data_7nopay_45pay.corr()

# data_7nopay_45pay_corr['prediction_pay_price'].sort_values(ascending=False)

# data_7nopay_45nopay=data_train2[(data_train2['pay_price']==0) &  (data_train2['prediction_pay_price']==0)]

# data_7nopay_45nopay_corr=data_7nopay_45nopay.corr()

# data_7nopay_45nopay_corr['prediction_pay_price'].sort_values(ascending=False)

# del data_7nopay_45pay_corr,data_7nopay_45nopay_corr,data_7nopay_corr
# del data_7nopay,data_7nopay_45nopay,data_7nopay_45pay

In [ ]:
data_train2[(data_train2['pay_price']==0) & (data_train2['prediction_pay_price']==0) & \
             #(data_train2['avg_online_minutes'] >75) 
             (data_train2['general_acceleration_add_value']> 100)].shape

In [ ]:
data_train2[(data_train2['pay_price']==0)]

In [ ]:
#################################################

In [ ]:
top50_ppp_index=data_train2[data_train2['prediction_pay_price']>0]['prediction_pay_price'].sort_values(ascending=False).head(50).index

In [ ]:
data_train2.iloc[top50_ppp_index][['avg_online_minutes','pay_count','pay_price','prediction_pay_price']]

In [ ]:
data_pp_df=data_train2[data_train2['pay_price']>0]

In [ ]:
data_pp_df=data_train2[data_train2['prediction_pay_price']>0]

In [ ]:
data_pp_df['pay_price'].describe()

In [ ]:
data_pp_df['prediction_pay_price'].describe()