In [1]:
import numpy as np
import pandas as pd

In [2]:
df_train=pd.read_csv('F:\\study\\ml\\DataSet\\Tap4fun\\tap_fun_test.csv')

In [3]:
df_train.info(memory_usage='deep')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 828934 entries, 0 to 828933
Columns: 108 entries, user_id to pay_count
dtypes: float64(4), int64(103), object(1)
memory usage: 736.8 MB

In [4]:
c_int=df_train.select_dtypes(include=['int64']).apply(pd.to_numeric,downcast='unsigned')
c_float=df_train.select_dtypes(include=['float']).apply(pd.to_numeric,downcast='float')

In [5]:
o_df=pd.concat([c_int,c_float],axis=1)

In [6]:
column_type=dict(o_df.dtypes.copy())

In [7]:
len(column_type)

107

In [8]:
del o_df,c_int,c_float,df_train

In [9]:
data_train=pd.read_csv('F:\\study\\ml\\DataSet\\Tap4fun\\tap_fun_test.csv',
                      dtype=column_type,parse_dates=['register_time'],infer_datetime_format=True)

In [10]:
data_train.rename(columns={'treatment_acceleraion_add_value':'treatment_acceleration_add_value',\
                          'sr_rss_a_prod_levell':'sr_rss_a_prod_level'} ,inplace=True)

In [11]:
data_train.head()

,user_id,register_time,wood_add_value,wood_reduce_value,stone_add_value,stone_reduce_value,ivory_add_value,ivory_reduce_value,meat_add_value,meat_reduce_value,...,sr_rss_help_bonus_level,pvp_battle_count,pvp_lanch_count,pvp_win_count,pve_battle_count,pve_lanch_count,pve_win_count,avg_online_minutes,pay_price,pay_count
0,14933,2018-03-08 20:27:57,166415.0,138362.0,0,0,0,0,258522,90142,...,0,0,0,0,1,1,1,8.000000,0.0,0
1,14934,2018-03-08 20:29:42,10000.0,600.0,0,0,0,0,10000,400,...,0,0,0,0,0,0,0,0.166667,0.0,0
2,14935,2018-03-08 20:30:13,10000.0,3700.0,0,0,0,0,10000,2000,...,0,0,0,0,0,0,0,17.000000,0.0,0
3,14936,2018-03-08 20:31:41,210000.0,0.0,200000,0,200000,0,610000,0,...,0,0,0,0,0,0,0,1.666667,0.0,0
4,14937,2018-03-08 20:32:07,11500.0,3700.0,0,0,0,0,11000,2000,...,0,0,0,0,0,0,0,0.333333,0.0,0

In [12]:
data_train.info(memory_usage='deep')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 828934 entries, 0 to 828933
Columns: 108 entries, user_id to pay_count
dtypes: datetime64[ns](1), float32(4), uint16(8), uint32(29), uint8(66)
memory usage: 175.5 MB

In [13]:
# data_label=data_train['prediction_pay_price']
data_train2=data_train.drop(labels=['user_id','register_time'],axis=1)

In [14]:
data_7pay=data_train2[data_train2['pay_price']>0].copy()

In [15]:
data_7pay.head()

,wood_add_value,wood_reduce_value,stone_add_value,stone_reduce_value,ivory_add_value,ivory_reduce_value,meat_add_value,meat_reduce_value,magic_add_value,magic_reduce_value,...,sr_rss_help_bonus_level,pvp_battle_count,pvp_lanch_count,pvp_win_count,pve_battle_count,pve_lanch_count,pve_win_count,avg_online_minutes,pay_price,pay_count
19,3838322.0,2859288.0,1041000,0,504000,0,6898146,4297996,228209,26500,...,0,4,4,4,4,4,3,27.166668,0.99,1
96,2353190.0,1286349.0,1000000,0,609000,0,3216753,513123,79405,52453,...,0,2,0,0,5,5,5,19.500000,0.99,1
126,6058137.0,3960541.0,5040000,2520000,2109000,0,14586512,7910807,230292,185600,...,0,0,0,0,11,11,9,13.833333,5.98,2
131,2958155.0,2350347.0,1364518,407296,600000,0,5895581,3241016,283404,125100,...,0,2,1,0,2,2,2,13.000000,0.99,1
169,1080008.0,19659.0,1000000,0,500000,0,2303911,13076,0,0,...,0,0,0,0,1,1,1,2.166667,0.99,1

In [16]:
for name in data_7pay.columns.values:
    if 'add_value' in name:
        print(name+'-->'+name[:len(name)-10])
print('------------------')        
for name in data_7pay.columns.values:
    if 'reduce_value' in name:
        print(name+'-->'+name[:len(name)-10])

wood_add_value-->wood
stone_add_value-->stone
ivory_add_value-->ivory
meat_add_value-->meat
magic_add_value-->magic
infantry_add_value-->infantry
cavalry_add_value-->cavalry
shaman_add_value-->shaman
wound_infantry_add_value-->wound_infantry
wound_cavalry_add_value-->wound_cavalry
wound_shaman_add_value-->wound_shaman
general_acceleration_add_value-->general_acceleration
building_acceleration_add_value-->building_acceleration
reaserch_acceleration_add_value-->reaserch_acceleration
training_acceleration_add_value-->training_acceleration
treatment_acceleration_add_value-->treatment_acceleration
------------------
wood_reduce_value-->wood_re
stone_reduce_value-->stone_re
ivory_reduce_value-->ivory_re
meat_reduce_value-->meat_re
magic_reduce_value-->magic_re
infantry_reduce_value-->infantry_re
cavalry_reduce_value-->cavalry_re
shaman_reduce_value-->shaman_re
wound_infantry_reduce_value-->wound_infantry_re
wound_cavalry_reduce_value-->wound_cavalry_re
wound_shaman_reduce_value-->wound_shaman_re
general_acceleration_reduce_value-->general_acceleration_re
building_acceleration_reduce_value-->building_acceleration_re
reaserch_acceleration_reduce_value-->reaserch_acceleration_re
training_acceleration_reduce_value-->training_acceleration_re
treatment_acceleration_reduce_value-->treatment_acceleration_re

In [17]:
sum_delta_text=[]
sum_delta_text=['wood','stone']
for name in data_7pay.columns.values:
    if 'add_value' in name:
        sum_delta_text.append(name[:len(name)-10])
        
for i in sum_delta_text:
#     print(i+'_add_value  <--> '+i+'_reduce_value')
    add_name=i+'_add_value'
    reduce_name=i+'_reduce_value'
    sum_name=i+'_sum_qua1'
    delta_name=i+'_delta_qua2'
    print(add_name+' -- '+reduce_name)
#     print(reduce_name)
#     print(sum_name)
#     print(delta_name)
    data_7pay[sum_name]=data_7pay[add_name]+data_7pay[reduce_name]
    data_7pay[delta_name]=data_7pay[add_name]-data_7pay[reduce_name]
#     for k in range(3):
#         print('------------------{}--------------'.format(k))
#         print(data_7pay[add_name].iloc[k])
#         print(data_7pay[reduce_name].iloc[k])
#         print(data_7pay[add_name].iloc[k]-data_7pay[reduce_name].iloc[k])

wood_add_value -- wood_reduce_value
stone_add_value -- stone_reduce_value
wood_add_value -- wood_reduce_value
stone_add_value -- stone_reduce_value
ivory_add_value -- ivory_reduce_value
meat_add_value -- meat_reduce_value
magic_add_value -- magic_reduce_value
infantry_add_value -- infantry_reduce_value
cavalry_add_value -- cavalry_reduce_value
shaman_add_value -- shaman_reduce_value
wound_infantry_add_value -- wound_infantry_reduce_value
wound_cavalry_add_value -- wound_cavalry_reduce_value
wound_shaman_add_value -- wound_shaman_reduce_value
general_acceleration_add_value -- general_acceleration_reduce_value
building_acceleration_add_value -- building_acceleration_reduce_value
reaserch_acceleration_add_value -- reaserch_acceleration_reduce_value
training_acceleration_add_value -- training_acceleration_reduce_value
treatment_acceleration_add_value -- treatment_acceleration_reduce_value

In [18]:
data_7pay.head()

,wood_add_value,wood_reduce_value,stone_add_value,stone_reduce_value,ivory_add_value,ivory_reduce_value,meat_add_value,meat_reduce_value,magic_add_value,magic_reduce_value,...,general_acceleration_sum_qua1,general_acceleration_delta_qua2,building_acceleration_sum_qua1,building_acceleration_delta_qua2,reaserch_acceleration_sum_qua1,reaserch_acceleration_delta_qua2,training_acceleration_sum_qua1,training_acceleration_delta_qua2,treatment_acceleration_sum_qua1,treatment_acceleration_delta_qua2
19,3838322.0,2859288.0,1041000,0,504000,0,6898146,4297996,228209,26500,...,514,478,4870,1382,6062,1278,429,105,94,94
96,2353190.0,1286349.0,1000000,0,609000,0,3216753,513123,79405,52453,...,415,415,4884,1770,4111,2329,659,659,15,15
126,6058137.0,3960541.0,5040000,2520000,2109000,0,14586512,7910807,230292,185600,...,379,25,10827,97,6293,4117,2581,2269,90,90
131,2958155.0,2350347.0,1364518,407296,600000,0,5895581,3241016,283404,125100,...,312,0,6978,0,5999,771,505,465,90,90
169,1080008.0,19659.0,1000000,0,500000,0,2303911,13076,0,0,...,3,3,2731,2731,2960,2960,95,95,0,0

In [19]:
data_7pay.head()

,wood_add_value,wood_reduce_value,stone_add_value,stone_reduce_value,ivory_add_value,ivory_reduce_value,meat_add_value,meat_reduce_value,magic_add_value,magic_reduce_value,...,general_acceleration_sum_qua1,general_acceleration_delta_qua2,building_acceleration_sum_qua1,building_acceleration_delta_qua2,reaserch_acceleration_sum_qua1,reaserch_acceleration_delta_qua2,training_acceleration_sum_qua1,training_acceleration_delta_qua2,treatment_acceleration_sum_qua1,treatment_acceleration_delta_qua2
19,3838322.0,2859288.0,1041000,0,504000,0,6898146,4297996,228209,26500,...,514,478,4870,1382,6062,1278,429,105,94,94
96,2353190.0,1286349.0,1000000,0,609000,0,3216753,513123,79405,52453,...,415,415,4884,1770,4111,2329,659,659,15,15
126,6058137.0,3960541.0,5040000,2520000,2109000,0,14586512,7910807,230292,185600,...,379,25,10827,97,6293,4117,2581,2269,90,90
131,2958155.0,2350347.0,1364518,407296,600000,0,5895581,3241016,283404,125100,...,312,0,6978,0,5999,771,505,465,90,90
169,1080008.0,19659.0,1000000,0,500000,0,2303911,13076,0,0,...,3,3,2731,2731,2960,2960,95,95,0,0

In [20]:
data_7pay['wood_sum_qua1'].head()

19      6697610.0
96      3639539.0
126    10018678.0
131     5308502.0
169     1099667.0
Name: wood_sum_qua1, dtype: float32

In [21]:
data_7pay['wood_delta_qua2'].head()

19      979034.0
96     1066841.0
126    2097596.0
131     607808.0
169    1060349.0
Name: wood_delta_qua2, dtype: float32

In [22]:
data_7pay.isna().sum().sum()

0

In [23]:
abs(-123.2)

123.2

In [24]:
delta_text=[]
for i in data_7pay.columns.values:
    if 'delta' in i:
        delta_text.append(i)
delta_text2=[]        
for k in delta_text:
    delta_text2.append(k[:len(k)-5]+'_abs_qua2')
print(delta_text2)

['wood_delta_abs_qua2', 'stone_delta_abs_qua2', 'ivory_delta_abs_qua2', 'meat_delta_abs_qua2', 'magic_delta_abs_qua2', 'infantry_delta_abs_qua2', 'cavalry_delta_abs_qua2', 'shaman_delta_abs_qua2', 'wound_infantry_delta_abs_qua2', 'wound_cavalry_delta_abs_qua2', 'wound_shaman_delta_abs_qua2', 'general_acceleration_delta_abs_qua2', 'building_acceleration_delta_abs_qua2', 'reaserch_acceleration_delta_abs_qua2', 'training_acceleration_delta_abs_qua2', 'treatment_acceleration_delta_abs_qua2']

In [25]:
data_7pay[delta_text2]=abs(data_7pay[delta_text])

In [26]:
data_7pay[delta_text].head()

,wood_delta_qua2,stone_delta_qua2,ivory_delta_qua2,meat_delta_qua2,magic_delta_qua2,infantry_delta_qua2,cavalry_delta_qua2,shaman_delta_qua2,wound_infantry_delta_qua2,wound_cavalry_delta_qua2,wound_shaman_delta_qua2,general_acceleration_delta_qua2,building_acceleration_delta_qua2,reaserch_acceleration_delta_qua2,training_acceleration_delta_qua2,treatment_acceleration_delta_qua2
19,979034.0,1041000,504000,2600150,201709,4294967289,129,4294967291,0,0,0,478,1382,1278,105,94
96,1066841.0,1000000,609000,2703630,26952,0,0,0,0,0,0,415,1770,2329,659,15
126,2097596.0,2520000,2109000,6675705,44692,205,135,135,0,0,0,25,97,4117,2269,90
131,607808.0,957222,600000,2654565,158304,4294967066,4294967276,0,40,40,0,0,0,771,465,90
169,1060349.0,1000000,500000,2290835,0,0,0,0,0,0,0,3,2731,2960,95,0

In [27]:
data_7pay[delta_text2].head()

,wood_delta_abs_qua2,stone_delta_abs_qua2,ivory_delta_abs_qua2,meat_delta_abs_qua2,magic_delta_abs_qua2,infantry_delta_abs_qua2,cavalry_delta_abs_qua2,shaman_delta_abs_qua2,wound_infantry_delta_abs_qua2,wound_cavalry_delta_abs_qua2,wound_shaman_delta_abs_qua2,general_acceleration_delta_abs_qua2,building_acceleration_delta_abs_qua2,reaserch_acceleration_delta_abs_qua2,training_acceleration_delta_abs_qua2,treatment_acceleration_delta_abs_qua2
19,979034.0,1041000.0,504000.0,2600150.0,201709.0,4.294967e+09,1.290000e+02,4.294967e+09,0.0,0.0,0.0,478.0,1382.0,1278.0,105.0,94.0
96,1066841.0,1000000.0,609000.0,2703630.0,26952.0,0.000000e+00,0.000000e+00,0.000000e+00,0.0,0.0,0.0,415.0,1770.0,2329.0,659.0,15.0
126,2097596.0,2520000.0,2109000.0,6675705.0,44692.0,2.050000e+02,1.350000e+02,1.350000e+02,0.0,0.0,0.0,25.0,97.0,4117.0,2269.0,90.0
131,607808.0,957222.0,600000.0,2654565.0,158304.0,4.294967e+09,4.294967e+09,0.000000e+00,40.0,40.0,0.0,0.0,0.0,771.0,465.0,90.0
169,1060349.0,1000000.0,500000.0,2290835.0,0.0,0.000000e+00,0.000000e+00,0.000000e+00,0.0,0.0,0.0,3.0,2731.0,2960.0,95.0,0.0

In [28]:
text_shaman=[]
for col in data_7pay.columns.values:
     if 'shaman' in col:
            text_shaman.append(col)
data_7pay[text_shaman]

,shaman_add_value,shaman_reduce_value,wound_shaman_add_value,wound_shaman_reduce_value,sr_shaman_tier_2_level,sr_shaman_atk_level,sr_shaman_tier_3_level,sr_shaman_def_level,sr_shaman_hp_level,sr_shaman_tier_4_level,shaman_sum_qua1,shaman_delta_qua2,wound_shaman_sum_qua1,wound_shaman_delta_qua2,shaman_delta_abs_qua2,wound_shaman_delta_abs_qua2
19,0,5,0,0,0,0,0,0,0,0,5,4294967291,0,0,4.294967e+09,0.0
96,280,280,280,280,0,0,0,0,0,0,560,0,560,0,0.000000e+00,0.0
126,135,0,0,0,0,0,0,0,0,0,135,135,0,0,1.350000e+02,0.0
131,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.000000e+00,0.0
169,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.000000e+00,0.0
184,708,923,478,478,0,0,0,0,0,0,1631,4294967081,956,0,4.294967e+09,0.0
277,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.000000e+00,0.0
309,1848,94,3,3,1,1,0,0,0,0,1942,1754,6,0,1.754000e+03,0.0
408,95,410,220,0,0,0,0,0,0,0,505,4294966981,220,220,4.294967e+09,220.0
470,324,3563,217,139,1,1,0,0,0,0,3887,4294964057,356,78,4.294964e+09,78.0
483,0,0,0,0,1,2,0,0,0,0,0,0,0,0,0.000000e+00,0.0
526,5283,4625,4578,4578,1,1,0,0,0,0,9908,658,9156,0,6.580000e+02,0.0
545,420,120,0,0,0,0,0,0,0,0,540,300,0,0,3.000000e+02,0.0
558,22722,28233,21867,21867,1,1,0,0,0,0,50955,4294961785,43734,0,4.294962e+09,0.0
559,18495,18777,17555,17555,1,4,0,0,0,0,37272,4294967014,35110,0,4.294967e+09,0.0
575,372,1102,372,372,1,0,0,0,0,0,1474,4294966566,744,0,4.294967e+09,0.0
581,1305,2030,2026,1305,1,0,0,0,0,0,3335,4294966571,3331,721,4.294967e+09,721.0
586,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0.000000e+00,0.0
619,682,847,2,2,1,0,0,0,0,0,1529,4294967131,4,0,4.294967e+09,0.0
686,100,100,100,100,1,1,0,0,0,0,200,0,200,0,0.000000e+00,0.0
725,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.000000e+00,0.0
768,1536,3657,546,546,1,0,0,0,0,0,5193,4294965175,1092,0,4.294965e+09,0.0
901,760,0,0,0,0,0,0,0,0,0,760,760,0,0,7.600000e+02,0.0
908,4694,5746,19,19,1,2,0,0,0,0,10440,4294966244,38,0,4.294966e+09,0.0
976,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.000000e+00,0.0
1027,25648,15316,1732,1713,1,5,1,4,8,0,40964,10332,3445,19,1.033200e+04,19.0
1333,2107,1949,1837,1837,1,0,0,0,0,0,4056,158,3674,0,1.580000e+02,0.0
1366,1694,2692,1364,1364,0,0,0,0,0,0,4386,4294966298,2728,0,4.294966e+09,0.0
1462,8924,7985,7679,7679,1,2,0,0,0,0,16909,939,15358,0,9.390000e+02,0.0
1526,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.000000e+00,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
827848,3053,928,38,38,1,1,0,0,0,0,3981,2125,76,0,2.125000e+03,0.0
827849,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.000000e+00,0.0
827852,2110,3535,2110,2110,1,0,0,0,0,0,5645,4294965871,4220,0,4.294966e+09,0.0
827925,2483,1324,403,403,1,0,0,0,0,0,3807,1159,806,0,1.159000e+03,0.0
828000,577,1819,17,17,1,2,0,0,0,0,2396,4294966054,34,0,4.294966e+09,0.0
828007,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.000000e+00,0.0
828021,5639,29,21,21,1,3,0,0,0,0,5668,5610,42,0,5.610000e+03,0.0
828030,900,1186,1176,900,0,0,0,0,0,0,2086,4294967010,2076,276,4.294967e+09,276.0
828041,5275,555,555,555,0,5,0,0,0,0,5830,4720,1110,0,4.720000e+03,0.0
828042,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.000000e+00,0.0
828102,225,0,0,0,0,0,0,0,0,0,225,225,0,0,2.250000e+02,0.0
828195,1709,2983,1709,1709,1,2,0,0,0,0,4692,4294966022,3418,0,4.294966e+09,0.0
828223,270,3,0,0,0,0,0,0,0,0,273,267,0,0,2.670000e+02,0.0
828237,760,4435,3829,0,1,1,0,0,0,0,5195,4294963621,3829,3829,4.294964e+09,3829.0
828239,2358,3058,1428,1428,1,1,0,0,0,0,5416,4294966596,2856,0,4.294967e+09,0.0
828251,4241,6517,2456,2456,1,3,0,0,0,0,10758,4294965020,4912,0,4.294965e+09,0.0
828269,8088,8502,7258,7258,1,1,0,0,0,0,16590,4294966882,14516,0,4.294967e+09,0.0
828305,630,2168,2164,440,0,0,0,0,0,0,2798,4294965758,2604,1724,4.294966e+09,1724.0
828321,0,635,0,0,1,0,0,0,0,0,635,4294966661,0,0,4.294967e+09,0.0
828348,0,1704,55,0,0,0,0,0,0,0,1704,4294965592,55,55,4.294966e+09,55.0
828406,155,540,0,0,1,1,0,0,0,0,695,4294966911,0,0,4.294967e+09,0.0
828552,957,1135,0,0,1,1,0,0,0,0,2092,4294967118,0,0,4.294967e+09,0.0
828609,1260,739,0,0,1,2,0,0,0,0,1999,521,0,0,5.210000e+02,0.0
828649,190,27,0,0,1,0,0,0,0,0,217,163,0,0,1.630000e+02,0.0
828735,4628,3398,318,318,1,2,0,0,0,0,8026,1230,636,0,1.230000e+03,0.0
828748,1033,1227,1033,1033,0,0,0,0,0,0,2260,4294967102,2066,0,4.294967e+09,0.0
828753,537,925,548,537,0,0,0,0,0,0,1462,4294966908,1085,11,4.294967e+09,11.0
828767,2610,2189,2180,2180,1,0,0,0,0,0,4799,421,4360,0,4.210000e+02,0.0
828782,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.000000e+00,0.0
828804,3652,3580,2212,2212,0,0,0,0,0,0,7232,72,4424,0,7.200000e+01,0.0

In [29]:
import re

In [30]:
re.findall(r'\d','sr_outpost_tier_3_level')

['3']

In [31]:
level1_text=[]
level2_text=[]
level3_text=[]
level4_text=[]
for i in data_7pay.columns.values:
    if 'level' in i:
        if re.findall(r'\d',i)==['2']:
            level2_text.append(i)
        elif re.findall(r'\d',i)==['3']:
            level3_text.append(i)
        elif re.findall(r'\d',i)==['4']:
            level4_text.append(i)
        else :
            level1_text.append(i)
print('-------------1 ----------')            
print(level1_text)
print('-------------2----------')            
print(level2_text)
print('-------------3 ----------')            
print(level3_text)
print('-------------4 ----------')            
print(level4_text)

-------------1 ----------
['bd_training_hut_level', 'bd_healing_lodge_level', 'bd_stronghold_level', 'bd_outpost_portal_level', 'bd_barrack_level', 'bd_healing_spring_level', 'bd_dolmen_level', 'bd_guest_cavern_level', 'bd_warehouse_level', 'bd_watchtower_level', 'bd_magic_coin_tree_level', 'bd_hall_of_war_level', 'bd_market_level', 'bd_hero_gacha_level', 'bd_hero_strengthen_level', 'bd_hero_pve_level', 'sr_scout_level', 'sr_training_speed_level', 'sr_infantry_atk_level', 'sr_cavalry_atk_level', 'sr_shaman_atk_level', 'sr_troop_defense_level', 'sr_infantry_def_level', 'sr_cavalry_def_level', 'sr_shaman_def_level', 'sr_infantry_hp_level', 'sr_cavalry_hp_level', 'sr_shaman_hp_level', 'sr_troop_attack_level', 'sr_construction_speed_level', 'sr_hide_storage_level', 'sr_troop_consumption_level', 'sr_rss_a_prod_level', 'sr_rss_b_prod_level', 'sr_rss_c_prod_level', 'sr_rss_d_prod_level', 'sr_rss_a_gather_level', 'sr_rss_b_gather_level', 'sr_rss_c_gather_level', 'sr_rss_d_gather_level', 'sr_troop_load_level', 'sr_rss_e_gather_level', 'sr_rss_e_prod_level', 'sr_outpost_durability_level', 'sr_healing_space_level', 'sr_gathering_hunter_buff_level', 'sr_healing_speed_level', 'sr_alliance_march_speed_level', 'sr_pvp_march_speed_level', 'sr_gathering_march_speed_level', 'sr_guest_troop_capacity_level', 'sr_march_size_level', 'sr_rss_help_bonus_level']
-------------2----------
['sr_infantry_tier_2_level', 'sr_cavalry_tier_2_level', 'sr_shaman_tier_2_level', 'sr_outpost_tier_2_level']
-------------3 ----------
['sr_infantry_tier_3_level', 'sr_cavalry_tier_3_level', 'sr_shaman_tier_3_level', 'sr_outpost_tier_3_level']
-------------4 ----------
['sr_infantry_tier_4_level', 'sr_cavalry_tier_4_level', 'sr_shaman_tier_4_level', 'sr_outpost_tier_4_level']

In [32]:
data_7pay[level1_text].head(30)

,bd_training_hut_level,bd_healing_lodge_level,bd_stronghold_level,bd_outpost_portal_level,bd_barrack_level,bd_healing_spring_level,bd_dolmen_level,bd_guest_cavern_level,bd_warehouse_level,bd_watchtower_level,...,sr_outpost_durability_level,sr_healing_space_level,sr_gathering_hunter_buff_level,sr_healing_speed_level,sr_alliance_march_speed_level,sr_pvp_march_speed_level,sr_gathering_march_speed_level,sr_guest_troop_capacity_level,sr_march_size_level,sr_rss_help_bonus_level
19,5,6,7,5,6,4,6,3,6,5,...,1,0,1,0,0,0,0,0,0,0
96,5,5,6,5,5,1,5,4,6,5,...,1,0,0,0,0,0,0,0,0,0
126,8,6,8,8,7,6,6,5,6,6,...,0,0,0,0,0,0,0,0,0,0
131,1,4,9,2,4,2,7,1,3,5,...,2,0,2,0,0,0,0,0,0,0
169,1,2,3,2,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
184,6,7,8,7,6,7,7,4,7,0,...,1,0,0,0,0,0,0,0,0,0
277,6,5,7,7,6,6,7,2,6,3,...,1,0,0,0,0,0,0,0,0,0
309,7,8,12,12,4,0,11,9,4,9,...,1,5,1,0,0,0,0,0,0,0
408,3,1,6,7,7,7,7,4,5,6,...,2,0,0,0,0,0,0,0,0,0
470,8,10,12,13,12,10,10,10,9,10,...,2,4,3,2,0,0,0,0,0,0
483,4,6,10,10,6,1,10,9,6,5,...,1,2,1,2,0,0,0,0,0,0
526,7,2,9,9,6,1,9,10,2,3,...,1,0,0,0,0,0,0,0,0,0
545,1,4,6,3,1,1,3,1,3,4,...,0,0,0,0,0,0,0,0,0,0
558,9,10,10,11,9,8,9,10,9,8,...,1,1,2,2,0,0,0,0,0,0
559,8,7,13,13,13,10,11,9,4,8,...,2,2,2,2,0,0,0,0,0,0
575,8,5,10,10,9,9,9,9,7,8,...,1,2,2,3,0,0,0,0,0,0
581,3,7,7,8,7,3,7,2,5,4,...,1,0,0,0,0,0,0,0,0,0
586,7,5,9,9,7,2,8,4,5,2,...,1,0,0,0,0,0,0,0,0,0
619,7,4,8,8,7,6,8,3,7,5,...,2,0,0,0,0,0,0,0,0,0
686,8,7,9,8,7,8,6,4,7,6,...,1,0,0,0,0,0,0,0,0,0
725,1,4,3,3,3,1,0,0,1,2,...,0,0,0,0,0,0,0,0,0,0
768,8,8,10,9,8,10,10,8,9,9,...,5,3,3,1,0,0,0,0,0,0
901,1,2,5,3,6,1,3,1,2,0,...,2,1,1,1,0,0,0,0,0,0
908,8,6,11,12,11,10,10,11,1,7,...,1,0,0,0,0,0,0,0,0,0
976,6,6,7,6,7,5,6,6,5,7,...,0,0,0,0,0,0,0,0,0,0
1027,9,5,16,18,14,14,17,14,14,7,...,1,1,3,4,0,0,0,0,0,0
1333,8,9,9,8,9,7,8,7,8,8,...,1,1,0,0,0,0,0,0,0,0
1366,7,8,8,7,8,8,8,8,7,8,...,1,0,0,0,0,0,0,0,0,0
1462,6,8,10,10,9,8,10,8,8,7,...,1,3,3,3,0,0,0,0,0,0
1526,1,1,1,4,4,1,2,0,4,2,...,0,0,0,0,0,0,0,0,0,0

In [33]:
data_7pay[level2_text].head(30)

,sr_infantry_tier_2_level,sr_cavalry_tier_2_level,sr_shaman_tier_2_level,sr_outpost_tier_2_level
19,0,0,0,1
96,0,0,0,0
126,0,0,0,0
131,0,0,0,1
169,0,0,0,0
184,0,1,0,0
277,0,0,0,0
309,1,1,1,1
408,0,0,0,1
470,1,1,1,1
483,1,1,1,1
526,1,1,1,1
545,0,0,0,0
558,1,1,1,1
559,1,1,1,1
575,1,1,1,1
581,0,1,1,1
586,1,1,1,1
619,1,1,1,1
686,1,1,1,0
725,0,0,0,0
768,1,1,1,1
901,0,0,0,1
908,1,1,1,1
976,0,0,0,0
1027,1,1,1,1
1333,1,1,1,1
1366,1,1,0,0
1462,1,1,1,1
1526,0,0,0,0

In [34]:
data_7pay[level3_text].head(30)

,sr_infantry_tier_3_level,sr_cavalry_tier_3_level,sr_shaman_tier_3_level,sr_outpost_tier_3_level
19,0,0,0,0
96,0,0,0,0
126,0,0,0,0
131,0,0,0,0
169,0,0,0,0
184,0,0,0,0
277,0,0,0,0
309,0,0,0,0
408,0,0,0,0
470,0,0,0,0
483,0,0,0,0
526,0,0,0,0
545,0,0,0,0
558,0,0,0,0
559,0,0,0,1
575,0,0,0,0
581,0,0,0,0
586,0,0,0,0
619,0,0,0,0
686,0,0,0,0
725,0,0,0,0
768,0,0,0,0
901,0,0,0,0
908,0,0,0,0
976,0,0,0,0
1027,1,1,1,1
1333,0,0,0,0
1366,0,0,0,0
1462,0,0,0,0
1526,0,0,0,0

In [35]:
data_7pay[level4_text].head(30)

,sr_infantry_tier_4_level,sr_cavalry_tier_4_level,sr_shaman_tier_4_level,sr_outpost_tier_4_level
19,0,0,0,0
96,0,0,0,0
126,0,0,0,0
131,0,0,0,0
169,0,0,0,0
184,0,0,0,0
277,0,0,0,0
309,0,0,0,0
408,0,0,0,0
470,0,0,0,0
483,0,0,0,0
526,0,0,0,0
545,0,0,0,0
558,0,0,0,0
559,0,0,0,0
575,0,0,0,0
581,0,0,0,0
586,0,0,0,0
619,0,0,0,0
686,0,0,0,0
725,0,0,0,0
768,0,0,0,0
901,0,0,0,0
908,0,0,0,0
976,0,0,0,0
1027,0,0,0,0
1333,0,0,0,0
1366,0,0,0,0
1462,0,0,0,0
1526,0,0,0,0

In [36]:
for i in level1_text:
    if 'shaman' in i:
        print(i)

sr_shaman_atk_level
sr_shaman_def_level
sr_shaman_hp_level

In [37]:
troop_text1=[]
for i in level1_text:
    if 'troop' in i:
        troop_text1.append(i)
data_7pay['troop_con_load_atk_def_sum_qua1']=0
for k in troop_text1:
    data_7pay['troop_con_load_atk_def_sum_qua1']+=data_7pay[k]

In [38]:
infantry_text1=[]
cavalry_text1=[]
shaman_text1=[]
outpost_text1=[]
for i in level1_text:
    if 'infantry' in i:
        infantry_text1.append(i)
    elif 'cavalry' in i:
        cavalry_text1.append(i)
    elif 'shaman' in i:
        shaman_text1.append(i)
    elif 'outpost' in i:
        outpost_text1.append(i)

In [39]:
for i in shaman_text1:
    print(i)

sr_shaman_atk_level
sr_shaman_def_level
sr_shaman_hp_level

In [40]:
data_7pay['infantry_hp_atk_def_sum_qua1']=0
data_7pay['cavalry_hp_atk_def_sum_qua1']=0
data_7pay['shaman_hp_atk_def_sum_qua1']=0
data_7pay['outpost_hp_atk_def_sum_qua1']=0
for i in infantry_text1:
    name='infantry_hp_atk_def_sum_qua1'
    data_7pay[name]+=data_7pay[i]
for i in cavalry_text1:
    name='cavalry_hp_atk_def_sum_qua1'
    data_7pay[name]+=data_7pay[i]
for i in shaman_text1:
    name='shaman_hp_atk_def_sum_qua1'
    data_7pay[name]+=data_7pay[i]    
for i in outpost_text1:
    name='outpost_hp_atk_def_sum_qua1'
    data_7pay[name]+=data_7pay[i]

In [41]:
data_7pay['infantry_tier_2_sum_qua2']=0
data_7pay['cavalry_tier_2_sum_qua2']=0
data_7pay['shaman_tier_2_sum_qua2']=0
data_7pay['outpost_tier_2_sum_qua2']=0
infantry_text2=[]
cavalry_text2=[]
shaman_text2=[]
outpost_text2=[]
for i in level2_text:
    if 'infantry' in i:
        infantry_text2.append(i)
    elif 'cavalry' in i:
        cavalry_text2.append(i)
    elif 'shaman' in i:
        shaman_text2.append(i)
    elif 'outpost' in i:
        outpost_text2.append(i)
##############################################        
for i in infantry_text2:
    name='infantry_tier_2_sum_qua2'
    data_7pay[name]+=data_7pay[i]
for i in cavalry_text2:
    name='cavalry_tier_2_sum_qua2'
    data_7pay[name]+=data_7pay[i]
for i in shaman_text2:
    name='shaman_tier_2_sum_qua2'
    data_7pay[name]+=data_7pay[i]    
for i in outpost_text2:
    name='outpost_tier_2_sum_qua2'
    data_7pay[name]+=data_7pay[i]

In [42]:
data_7pay['infantry_tier_3_sum_qua3']=0
data_7pay['cavalry_tier_3_sum_qua3']=0
data_7pay['shaman_tier_3_sum_qua3']=0
data_7pay['outpost_tier_3_sum_qua3']=0
infantry_text3=[]
cavalry_text3=[]
shaman_text3=[]
outpost_text3=[]
for i in level3_text:
    if 'infantry' in i:
        infantry_text3.append(i)
    elif 'cavalry' in i:
        cavalry_text3.append(i)
    elif 'shaman' in i:
        shaman_text3.append(i)
    elif 'outpost' in i:
        outpost_text3.append(i)
##############################################        
for i in infantry_text3:
    name='infantry_tier_3_sum_qua3'
    data_7pay[name]+=data_7pay[i]
for i in cavalry_text3:
    name='cavalry_tier_3_sum_qua3'
    data_7pay[name]+=data_7pay[i]
for i in shaman_text3:
    name='shaman_tier_3_sum_qua3'
    data_7pay[name]+=data_7pay[i]    
for i in outpost_text3:
    name='outpost_tier_3_sum_qua3'
    data_7pay[name]+=data_7pay[i]

In [43]:
data_7pay['infantry_tier_4_sum_qua4']=0
data_7pay['cavalry_tier_4_sum_qua4']=0
data_7pay['shaman_tier_4_sum_qua4']=0
data_7pay['outpost_tier_4_sum_qua4']=0
infantry_text4=[]
cavalry_text4=[]
shaman_text4=[]
outpost_text4=[]
for i in level4_text:
    if 'infantry' in i:
        infantry_text4.append(i)
    elif 'cavalry' in i:
        cavalry_text4.append(i)
    elif 'shaman' in i:
        shaman_text4.append(i)
    elif 'outpost' in i:
        outpost_text4.append(i)
##############################################        
for i in infantry_text4:
    name='infantry_tier_4_sum_qua4'
    data_7pay[name]+=data_7pay[i]
for i in cavalry_text4:
    name='cavalry_tier_4_sum_qua4'
    data_7pay[name]+=data_7pay[i]
for i in shaman_text4:
    name='shaman_tier_4_sum_qua4'
    data_7pay[name]+=data_7pay[i]    
for i in outpost_text4:
    name='outpost_tier_4_sum_qua4'
    data_7pay[name]+=data_7pay[i]

In [44]:
rss_test=[]
for i in data_7pay.columns.values:
    if 'rss' in i:
        rss_test.append(i)
        print(i[:9])

sr_rss_a_
sr_rss_b_
sr_rss_c_
sr_rss_d_
sr_rss_a_
sr_rss_b_
sr_rss_c_
sr_rss_d_
sr_rss_e_
sr_rss_e_
sr_rss_he

In [45]:
for i in data_7pay.columns.values:
    if 'sr_rss_c' in i:
        print(i)

sr_rss_c_prod_level
sr_rss_c_gather_level

In [46]:
for i in rss_test:
    if 'prod' in i:
        col_name=i[:9]+'sum_qua1'
        prod_name=i[:9]+'prod_level'
        gather_name=i[:9]+'gather_level'
        data_7pay[col_name]=data_7pay[prod_name]+data_7pay[gather_name]

In [47]:
data_7pay.head()

,wood_add_value,wood_reduce_value,stone_add_value,stone_reduce_value,ivory_add_value,ivory_reduce_value,meat_add_value,meat_reduce_value,magic_add_value,magic_reduce_value,...,outpost_tier_3_sum_qua3,infantry_tier_4_sum_qua4,cavalry_tier_4_sum_qua4,shaman_tier_4_sum_qua4,outpost_tier_4_sum_qua4,sr_rss_a_sum_qua1,sr_rss_b_sum_qua1,sr_rss_c_sum_qua1,sr_rss_d_sum_qua1,sr_rss_e_sum_qua1
19,3838322.0,2859288.0,1041000,0,504000,0,6898146,4297996,228209,26500,...,0,0,0,0,0,0,0,0,0,0
96,2353190.0,1286349.0,1000000,0,609000,0,3216753,513123,79405,52453,...,0,0,0,0,0,0,0,0,0,0
126,6058137.0,3960541.0,5040000,2520000,2109000,0,14586512,7910807,230292,185600,...,0,0,0,0,0,0,0,0,0,0
131,2958155.0,2350347.0,1364518,407296,600000,0,5895581,3241016,283404,125100,...,0,0,0,0,0,0,0,0,0,0
169,1080008.0,19659.0,1000000,0,500000,0,2303911,13076,0,0,...,0,0,0,0,0,0,0,0,0,0

In [48]:
data_7pay[[ i for i in data_7pay.columns.values if 'troop' in i ]].head()

,sr_troop_defense_level,sr_troop_attack_level,sr_troop_consumption_level,sr_troop_load_level,sr_guest_troop_capacity_level,troop_con_load_atk_def_sum_qua1
19,0,0,1,0,0,1
96,0,0,0,0,0,0
126,0,0,0,0,0,0
131,0,0,1,0,0,1
169,0,0,0,0,0,0

In [49]:
bd_healing_text1=[]
for i in level1_text:
    if 'bd_healing' in i:
        bd_healing_text1.append(i)
data_7pay['bd_healing_sum_qua1']=0
for k in bd_healing_text1:
    data_7pay['bd_healing_sum_qua1']+=data_7pay[k]

In [50]:
bd_hero_text1=[]
for i in level1_text:
    if 'bd_hero' in i:
        bd_hero_text1.append(i)
data_7pay['bd_hero_sum_qua1']=0
for k in bd_hero_text1:
    data_7pay['bd_hero_sum_qua1']+=data_7pay[k]

In [51]:
sr_text1=[]
for i in level1_text:
    if 'sr' in i:
        sr_text1.append(i)
data_7pay['sr1_sum_qua1']=0
for k in sr_text1:
    data_7pay['sr1_sum_qua1']+=data_7pay[k]
    
########################
sr_text2=[]
for i in level2_text:
    if 'sr' in i:
        sr_text2.append(i)
data_7pay['sr2_sum_qua1']=0
for k in sr_text2:
    data_7pay['sr2_sum_qua1']+=data_7pay[k]

#########################
sr_text3=[]
for i in level3_text:
    if 'sr' in i:
        sr_text3.append(i)
data_7pay['sr3_sum_qua1']=0
for k in sr_text3:
    data_7pay['sr3_sum_qua1']+=data_7pay[k]
    
#######################    
sr_text4=[]
for i in level4_text:
    if 'sr' in i:
        sr_text4.append(i)
data_7pay['sr4_sum_qua1']=0
for k in sr_text4:
    data_7pay['sr4_sum_qua1']+=data_7pay[k]

In [52]:
bd_text1=[]
for i in level1_text:
    if 'bd' in i:
        bd_text1.append(i)
data_7pay['bd1_sum_qua1']=0
for k in bd_text1:
    data_7pay['bd1_sum_qua1']+=data_7pay[k]

In [53]:
sr1_atk_text=[]
for i in level1_text:
    if 'atk_level' in i:
        sr1_atk_text.append(i)
data_7pay['sr1_atk_sum_qua1']=0
for k in sr1_atk_text:
    data_7pay['sr1_atk_sum_qua1']+=data_7pay[k]
    
#####################
sr1_def_text=[]
for i in level1_text:
    if 'def_level' in i:
        sr1_def_text.append(i)
data_7pay['sr1_def_sum_qua1']=0
for k in sr1_def_text:
    data_7pay['sr1_def_sum_qua1']+=data_7pay[k]

####################

sr1_hp_text=[]
for i in level1_text:
    if 'hp_level' in i:
        sr1_hp_text.append(i)
data_7pay['sr1_hp_sum_qua1']=0
for k in sr1_hp_text:
    data_7pay['sr1_hp_sum_qua1']+=data_7pay[k]

In [54]:
soldier_name=['shaman','cavalry','infantry']
properity_name=['hp','atk','def']
for i in soldier_name:
    for k in properity_name:
        sum_name=i+'_hp_atk_def_sum_qua1'
        name='sr_'+i+'_'+k+'_level'
        col_name=i+'_'+k+'_sum_rate_qua4'
#         print(data_7pay[name].shape[0])
        data_7pay[col_name]=data_7pay[name]/data_7pay[sum_name]

In [55]:
pvp_text1=[]
for i in data_7pay.columns.values:
    if ('pvp' in i) & ('count' in i):
        pvp_text1.append(i)
data_7pay['pvp_sum_qua1']=0
for k in pvp_text1:
    data_7pay['pvp_sum_qua1']+=data_7pay[k]

In [56]:
pve_text1=[]
for i in data_7pay.columns.values:
    if ('pve' in i) & ('count' in i):
        pve_text1.append(i)
data_7pay['pve_sum_qua1']=0
for k in pve_text1:
    data_7pay['pve_sum_qua1']+=data_7pay[k]

In [57]:
data_7pay['pvp_win_battle_rate_qua4']=data_7pay['pvp_win_count']/data_7pay['pvp_battle_count']
data_7pay['pve_win_battle_rate_qua4']=data_7pay['pve_win_count']/data_7pay['pve_battle_count']
data_7pay['pvp_lanch_battle_rate_qua4']=data_7pay['pvp_lanch_count']/data_7pay['pvp_battle_count']
data_7pay['pve_lanch_battle_rate_qua4']=data_7pay['pve_lanch_count']/data_7pay['pve_battle_count']

In [58]:
for name in data_7pay.columns.values:
    price_name=name+'_per_price_qua4'
    count_name=name+'_per_count_qua4'
    online_name=name+'_per_minute_qua4'
    data_7pay[price_name]=data_7pay[name] / data_7pay['pay_price']
    data_7pay[count_name]=data_7pay[name] / data_7pay['pay_count']
    data_7pay[online_name]=data_7pay[name] / data_7pay['avg_online_minutes']

In [59]:
data_7pay.head()

,wood_add_value,wood_reduce_value,stone_add_value,stone_reduce_value,ivory_add_value,ivory_reduce_value,meat_add_value,meat_reduce_value,magic_add_value,magic_reduce_value,...,pvp_win_battle_rate_qua4_per_minute_qua4,pve_win_battle_rate_qua4_per_price_qua4,pve_win_battle_rate_qua4_per_count_qua4,pve_win_battle_rate_qua4_per_minute_qua4,pvp_lanch_battle_rate_qua4_per_price_qua4,pvp_lanch_battle_rate_qua4_per_count_qua4,pvp_lanch_battle_rate_qua4_per_minute_qua4,pve_lanch_battle_rate_qua4_per_price_qua4,pve_lanch_battle_rate_qua4_per_count_qua4,pve_lanch_battle_rate_qua4_per_minute_qua4
19,3838322.0,2859288.0,1041000,0,504000,0,6898146,4297996,228209,26500,...,0.03681,0.757576,0.750000,0.027607,1.010101,1.0,0.036810,1.010101,1.0,0.036810
96,2353190.0,1286349.0,1000000,0,609000,0,3216753,513123,79405,52453,...,0.00000,1.010101,1.000000,0.051282,0.000000,0.0,0.000000,1.010101,1.0,0.051282
126,6058137.0,3960541.0,5040000,2520000,2109000,0,14586512,7910807,230292,185600,...,NaN,0.136820,0.409091,0.059146,NaN,NaN,NaN,0.167224,0.5,0.072289
131,2958155.0,2350347.0,1364518,407296,600000,0,5895581,3241016,283404,125100,...,0.00000,1.010101,1.000000,0.076923,0.505051,0.5,0.038462,1.010101,1.0,0.076923
169,1080008.0,19659.0,1000000,0,500000,0,2303911,13076,0,0,...,NaN,1.010101,1.000000,0.461538,NaN,NaN,NaN,1.010101,1.0,0.461538

In [60]:
###########################

In [63]:
from  sklearn.externals import joblib

In [64]:
c_model = joblib.load(filename='F:\\study\\ml\\DataSet\\Tap4fun\\Model\\tf_model_c_20180830145339.gz')

In [65]:
data_train.shape

(828934, 108)

In [66]:
data_7pay.shape

(19549, 804)

In [68]:
ypred2=c_model.predict(data_7pay)

In [69]:
ypred=pd.Series()
for i in range(ypred2.shape[0]):
    if ypred2[i]>0.5:
        ypred.loc[i]=1
    else :
        ypred.loc[i]=0

In [70]:
data_7pay['target_class']=ypred

In [72]:
data_45pay=data_7pay[data_7pay['target_class']==1]

In [ ]:
##################### regression

In [73]:
r_model = joblib.load(filename='F:\\study\\ml\\DataSet\\Tap4fun\\Model\\tf_model_r_20180830150115.gz')

In [75]:
ypred3=pd.Series()
ypred3=r_model.predict(data_45pay)

In [77]:
ypred3[:3]

array([  10.02281189, 1437.86235053,  130.4739729 ])

In [78]:
data_45pay['prediction_pay_price']=ypred3

D:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [79]:
data_45pay['prediction_pay_price'].head()

96       10.022812
126    1437.862351
309     130.473973
483      68.395945
559      86.936644
Name: prediction_pay_price, dtype: float64

In [81]:
data_7pay['prediction_pay_price']=data_7pay['pay_price']
data_7pay.loc[data_7pay['target_class']==1,'prediction_pay_price']=data_45pay['prediction_pay_price']

In [82]:
data_7pay['prediction_pay_price'].head()

19        0.990000
96       10.022812
126    1437.862305
131       0.990000
169       0.990000
Name: prediction_pay_price, dtype: float32

In [83]:
data_train.head()

,user_id,register_time,wood_add_value,wood_reduce_value,stone_add_value,stone_reduce_value,ivory_add_value,ivory_reduce_value,meat_add_value,meat_reduce_value,...,sr_rss_help_bonus_level,pvp_battle_count,pvp_lanch_count,pvp_win_count,pve_battle_count,pve_lanch_count,pve_win_count,avg_online_minutes,pay_price,pay_count
0,14933,2018-03-08 20:27:57,166415.0,138362.0,0,0,0,0,258522,90142,...,0,0,0,0,1,1,1,8.000000,0.0,0
1,14934,2018-03-08 20:29:42,10000.0,600.0,0,0,0,0,10000,400,...,0,0,0,0,0,0,0,0.166667,0.0,0
2,14935,2018-03-08 20:30:13,10000.0,3700.0,0,0,0,0,10000,2000,...,0,0,0,0,0,0,0,17.000000,0.0,0
3,14936,2018-03-08 20:31:41,210000.0,0.0,200000,0,200000,0,610000,0,...,0,0,0,0,0,0,0,1.666667,0.0,0
4,14937,2018-03-08 20:32:07,11500.0,3700.0,0,0,0,0,11000,2000,...,0,0,0,0,0,0,0,0.333333,0.0,0

In [84]:
data_train['prediction_pay_price']=0
data_train.loc[data_train['pay_price']>0,'prediction_pay_price']=data_7pay['prediction_pay_price']

In [ ]:
nowTime=datetime.datetime.now().strftime('%Y%m%d%H%M%S')
name='tf_model_r_'+str(nowTime)+'.gz'
joblib.dump(gbm,'F:\\study\\ml\\DataSet\\Tap4fun\\Model\\'+name,compress=3)

In [86]:
result=pd.DataFrame()
result['user_id']=data_train.user_id
result['prediction_pay_price']=data_train.prediction_pay_price

In [87]:
result.head()

   user_id  prediction_pay_price
0    14933                   0.0
1    14934                   0.0
2    14935                   0.0
3    14936                   0.0
4    14937                   0.0

In [90]:
import datetime

In [91]:
nowTime=datetime.datetime.now().strftime('%Y%m%d%H%M%S')
name='tf_'+str(nowTime)
result.to_csv("F:\\study\\ml\\DataSet\\Tap4fun\\SubMission\\"+name+'.csv',index=False,encoding='utf-8')

In [ ]:
train_data4=data_45pay.copy()
train_data4.fillna(0,inplace=True)
train_data4_x=train_data4.drop(labels=['prediction_pay_price','prediction_pay_price_per_price_qua4',
                                      'prediction_pay_price_per_count_qua4','prediction_pay_price_per_minute_qua4',
                                      'prediction_pay_rate_qua4','prediction_pay_diff_qua2'],axis=1)
train_data4_y=train_data4['prediction_pay_price']
X_train4,X_test4,y_train4,y_test4=train_test_split(train_data4_x,train_data4_y,random_state=7,test_size=0.3)
train4=lgb.Dataset(X_train4,y_train4)
test4=lgb.Dataset(X_test4,label=y_test4,reference=train4)

params={
    'boosting_type':'gbdt',
    'objective':'mse',
    'metric':'rmse',
    'min_child_weigth':3,
    'num_leaves':2**5,
    'lambda_l2':10,
    'subsample':0.7,
    'colsample_bytree':0.7,
    'colsample_bylevel':0.7,
    'learning_rate':0.05,
    'tree_method':'exact',
    'seed':2017,
    'nthread':4,
    'silent':True
}


n=3000
gbm=lgb.train(params=params,
             train_set=train4,
             num_boost_round=n,
             verbose_eval=50,
             valid_sets=[train4,test4])

In [ ]:
nowTime=datetime.datetime.now().strftime('%Y%m%d%H%M%S')
name='tf_model_r_'+str(nowTime)+'.gz'
joblib.dump(gbm,'F:\\study\\ml\\DataSet\\Tap4fun\\Model\\'+name,compress=3)

In [ ]:
######################## linear regression

In [ ]:
# from sklearn.linear_model import LinearRegression

# data_7pay.isna().sum().sum()

# train_data3=data_7pay.copy()
# train_data3.fillna(0,inplace=True)

# train_data3.isna().sum().sum()

# ################    7pay
# train_data3=data_7pay.copy()
# train_data3.fillna(0,inplace=True)


# train_data3.isnull().any(axis=0).sum()

# train_data3.isnull().any(axis=1).sum()

# data.isnull().any()

# train_data3[train_data3.isnull().values==True]

# train_data3.shape

# dtrain_data3f=train_data3.dropna(axis=1)

# train_data3.shape

# np.any(np.isnan(train_data3))

In [ ]:
# train_data3_x=train_data3.drop(labels=['prediction_pay_price','prediction_pay_price_per_price_qua4',
#                                       'prediction_pay_price_per_count_qua4','prediction_pay_price_per_minute_qua4',
#                                       'prediction_pay_rate_qua4','prediction_pay_diff_qua2'],axis=1)
# train_data3_y=train_data3['prediction_pay_price']
# X_train3,X_test3,y_train3,y_test3=train_test_split(train_data3_x,train_data3_y,random_state=13,test_size=0.3)

# from sklearn.linear_model import LinearRegression
# lr=LinearRegression()
# lr.fit(X_train3,y_train3)

# y_prob3=lr.predict(X_test3)

# from sklearn.metrics import mean_squared_error

# np.sqrt(mean_squared_error(y_test3,y_prob3))

In [ ]:
################    7pay
train_data4=data_45pay.copy()
train_data4.fillna(0,inplace=True)
train_data4_x=train_data4.drop(labels=['prediction_pay_price','prediction_pay_price_per_price_qua4',
                                      'prediction_pay_price_per_count_qua4','prediction_pay_price_per_minute_qua4',
                                      'prediction_pay_rate_qua4','prediction_pay_diff_qua2'],axis=1)
train_data4_y=train_data4['prediction_pay_price']
X_train4,X_test4,y_train4,y_test4=train_test_split(train_data4_x,train_data4_y,random_state=7,test_size=0.3)

from sklearn.linear_model import LinearRegression
lr=LinearRegression()
lr.fit(X_train4,y_train4)

y_prob4=lr.predict(X_test4)

from sklearn.metrics import mean_squared_error

np.sqrt(mean_squared_error(y_test4,y_prob4))